// This file is auto-generated by oagen. Do not edit.

package com.workos

import com.workos.common.http.BaseClient
import com.workos.common.http.RetryConfig
import com.workos.common.json.ObjectMapperFactory
import okhttp3.OkHttpClient
import java.util.Properties
import java.util.concurrent.ConcurrentHashMap
import kotlin.reflect.KClass

/**
 * Top-level WorkOS SDK client.
 *
 * All configuration (API key, base URL, HTTP client, retry settings) is
 * instance-scoped — there is no mutable global state. Service accessors are
 * generated by oagen and deep-merged into this class as `val` properties.
 *
 * @oagen-ignore
 */
@Suppress("ktlint:standard:annotation")
open class WorkOS @JvmOverloads constructor(
  @JvmField val apiKey: String,
  @JvmField val clientId: String? = null,
  apiBaseUrl: String = DEFAULT_BASE_URL,
  @JvmField val httpClient: OkHttpClient = defaultHttpClient(),
  retryConfig: RetryConfig = RetryConfig.DEFAULT
) {
  @JvmField
  val apiBaseUrl: String = apiBaseUrl

  @JvmField
  val version: String = loadVersion()

  @JvmField
  val baseClient: BaseClient =
    BaseClient(
      apiKey = apiKey,
      apiBaseUrl = apiBaseUrl,
      httpClient = httpClient,
      objectMapper = ObjectMapperFactory.create(),
      retryConfig = retryConfig,
      userAgent = "workos-kotlin/$version"
    )

  private val serviceCache: ConcurrentHashMap<KClass<*>, Any> = ConcurrentHashMap()

  /** Used by generated service accessors — one instance per service per client. */
  @Suppress("UNCHECKED_CAST")
  fun <T : Any> service(
    cls: KClass<T>,
    factory: () -> T
  ): T = serviceCache.computeIfAbsent(cls) { factory() } as T

  companion object {
    const val DEFAULT_BASE_URL: String = "https://api.workos.com"

    private fun defaultHttpClient(): OkHttpClient =
      OkHttpClient
        .Builder()
        .callTimeout(30, java.util.concurrent.TimeUnit.SECONDS)
        .build()

    private fun loadVersion(): String {
      val resource = WorkOS::class.java.getResourceAsStream("/version.properties") ?: return "dev"
      return resource.use { stream ->
        Properties().apply { load(stream) }.getProperty("version", "dev")
      }
    }
  }

  /** Lazily-constructed [AdminPortal] accessor for this [WorkOS] client. */
  val adminPortal: com.workos.adminportal.AdminPortal
    get() = service(com.workos.adminportal.AdminPortal::class) { com.workos.adminportal.AdminPortal(this) }

  /** Lazily-constructed [ApiKeys] accessor for this [WorkOS] client. */
  val apiKeys: com.workos.apikeys.ApiKeys
    get() = service(com.workos.apikeys.ApiKeys::class) { com.workos.apikeys.ApiKeys(this) }

  /** Lazily-constructed [AuditLogs] accessor for this [WorkOS] client. */
  val auditLogs: com.workos.auditlogs.AuditLogs
    get() = service(com.workos.auditlogs.AuditLogs::class) { com.workos.auditlogs.AuditLogs(this) }

  /** Lazily-constructed [Authorization] accessor for this [WorkOS] client. */
  val authorization: com.workos.authorization.Authorization
    get() = service(com.workos.authorization.Authorization::class) { com.workos.authorization.Authorization(this) }

  /** Lazily-constructed [Connect] accessor for this [WorkOS] client. */
  val connect: com.workos.connect.Connect
    get() = service(com.workos.connect.Connect::class) { com.workos.connect.Connect(this) }

  /** Lazily-constructed [DirectorySync] accessor for this [WorkOS] client. */
  val directorySync: com.workos.directorysync.DirectorySync
    get() = service(com.workos.directorysync.DirectorySync::class) { com.workos.directorysync.DirectorySync(this) }

  /** Lazily-constructed [Events] accessor for this [WorkOS] client. */
  val events: com.workos.events.Events
    get() = service(com.workos.events.Events::class) { com.workos.events.Events(this) }

  /** Lazily-constructed [FeatureFlags] accessor for this [WorkOS] client. */
  val featureFlags: com.workos.featureflags.FeatureFlags
    get() = service(com.workos.featureflags.FeatureFlags::class) { com.workos.featureflags.FeatureFlags(this) }

  /** Lazily-constructed [MultiFactorAuth] accessor for this [WorkOS] client. */
  val multiFactorAuth: com.workos.multifactorauth.MultiFactorAuth
    get() = service(com.workos.multifactorauth.MultiFactorAuth::class) { com.workos.multifactorauth.MultiFactorAuth(this) }

  /** Lazily-constructed [OrganizationDomains] accessor for this [WorkOS] client. */
  val organizationDomains: com.workos.organizationdomains.OrganizationDomains
    get() = service(com.workos.organizationdomains.OrganizationDomains::class) { com.workos.organizationdomains.OrganizationDomains(this) }

  /** Lazily-constructed [Organizations] accessor for this [WorkOS] client. */
  val organizations: com.workos.organizations.Organizations
    get() = service(com.workos.organizations.Organizations::class) { com.workos.organizations.Organizations(this) }

  /** Lazily-constructed [Pipes] accessor for this [WorkOS] client. */
  val pipes: com.workos.pipes.Pipes
    get() = service(com.workos.pipes.Pipes::class) { com.workos.pipes.Pipes(this) }

  /** Lazily-constructed [Radar] accessor for this [WorkOS] client. */
  val radar: com.workos.radar.Radar
    get() = service(com.workos.radar.Radar::class) { com.workos.radar.Radar(this) }

  /** Lazily-constructed [SSO] accessor for this [WorkOS] client. */
  val sso: com.workos.sso.SSO
    get() = service(com.workos.sso.SSO::class) { com.workos.sso.SSO(this) }

  /** Lazily-constructed [UserManagement] accessor for this [WorkOS] client. */
  val userManagement: com.workos.usermanagement.UserManagement
    get() = service(com.workos.usermanagement.UserManagement::class) { com.workos.usermanagement.UserManagement(this) }

  /** Lazily-constructed [Webhooks] accessor for this [WorkOS] client. */
  val webhooks: com.workos.webhooks.Webhooks
    get() = service(com.workos.webhooks.Webhooks::class) { com.workos.webhooks.Webhooks(this) }

  /** Lazily-constructed [Widgets] accessor for this [WorkOS] client. */
  val widgets: com.workos.widgets.Widgets
    get() = service(com.workos.widgets.Widgets::class) { com.workos.widgets.Widgets(this) }
}
