// This file is auto-generated by oagen. Do not edit.

package com.workos

import com.workos.adminportal.AdminPortal
import com.workos.apikeys.ApiKeys
import com.workos.auditlogs.AuditLogs
import com.workos.authorization.Authorization
import com.workos.common.http.BaseClient
import com.workos.common.http.RetryConfig
import com.workos.common.json.ObjectMapperFactory
import com.workos.connect.Connect
import com.workos.directorysync.DirectorySync
import com.workos.events.Events
import com.workos.featureflags.FeatureFlags
import com.workos.groups.Groups
import com.workos.multifactorauth.MultiFactorAuth
import com.workos.organizationdomains.OrganizationDomains
import com.workos.organizations.Organizations
import com.workos.pipes.Pipes
import com.workos.radar.Radar
import com.workos.sso.SSO
import com.workos.usermanagement.UserManagement
import com.workos.usermanagementorganizationmembershipgroups.UserManagementOrganizationMembershipGroups
import com.workos.webhooks.Webhooks
import com.workos.widgets.Widgets
import okhttp3.OkHttpClient
import java.util.Properties
import java.util.concurrent.ConcurrentHashMap
import kotlin.reflect.KClass

/**
 * Top-level WorkOS SDK client.
 *
 * All configuration (API key, base URL, HTTP client, retry settings) is
 * instance-scoped — there is no mutable global state. Service accessors are
 * generated by oagen and deep-merged into this class as `val` properties.
 *
 * @oagen-ignore
 */
open class WorkOS
  @JvmOverloads
  constructor(
    /** The WorkOS API key used to authenticate requests. */
    @JvmField val apiKey: String,
    /** Optional WorkOS client ID, required for OAuth/PKCE flows. */
    @JvmField val clientId: String? = null,
    /** Base URL for all API requests (defaults to [DEFAULT_BASE_URL]). */
    @JvmField val apiBaseUrl: String = DEFAULT_BASE_URL,
    /** The OkHttp client used for all HTTP requests. */
    @JvmField val httpClient: OkHttpClient = defaultHttpClient(),
    /** Retry policy applied to transient HTTP failures. */
    @JvmField val retryConfig: RetryConfig = RetryConfig.DEFAULT
  ) {
    /** SDK version string loaded from `version.properties` at build time. */
    @JvmField
    val version: String = loadVersion()

    /** Low-level HTTP client shared by all service accessors. */
    @JvmField
    val baseClient: BaseClient =
      BaseClient(
        apiKey = apiKey,
        apiBaseUrl = apiBaseUrl,
        httpClient = httpClient,
        objectMapper = ObjectMapperFactory.create(),
        retryConfig = retryConfig,
        userAgent = "workos-kotlin/$version"
      )

    private val serviceCache: ConcurrentHashMap<KClass<*>, Any> = ConcurrentHashMap()

    /**
     * Used by hand-written extension-property service accessors (e.g.
     * `WorkOS.actions`, `WorkOS.session`) that cannot be expressed as
     * `by lazy` because they live outside the [WorkOS] class. Generated
     * service accessors use `by lazy` directly.
     */
    @Suppress("UNCHECKED_CAST")
    fun <T : Any> service(
      cls: KClass<T>,
      factory: () -> T
    ): T = serviceCache.computeIfAbsent(cls) { factory() } as T

    /**
     * Fluent builder for [WorkOS], primarily intended for Java callers who
     * cannot easily use Kotlin named/default arguments.
     *
     * Kotlin usage:
     * ```kotlin
     * val workos = WorkOS.builder()
     *   .apiKey("sk_test_xxx")
     *   .retryConfig(RetryConfig.DISABLED)
     *   .build()
     * ```
     *
     * Java usage:
     * ```java
     * WorkOS workos = WorkOS.builder()
     *     .apiKey("sk_test_xxx")
     *     .retryConfig(RetryConfig.DISABLED)
     *     .build();
     * ```
     */
    class Builder {
      private var apiKey: String? = null
      private var clientId: String? = null
      private var apiBaseUrl: String = DEFAULT_BASE_URL
      private var httpClient: OkHttpClient? = null
      private var retryConfig: RetryConfig = RetryConfig.DEFAULT

      /** Sets the WorkOS API key (required). */
      fun apiKey(apiKey: String): Builder = apply { this.apiKey = apiKey }

      /** Sets the WorkOS client ID (required for OAuth/PKCE flows). */
      fun clientId(clientId: String?): Builder = apply { this.clientId = clientId }

      /** Sets the base URL for all API requests (defaults to [DEFAULT_BASE_URL]). */
      fun apiBaseUrl(apiBaseUrl: String): Builder = apply { this.apiBaseUrl = apiBaseUrl }

      /** Sets the OkHttp client used for all HTTP requests. */
      fun httpClient(httpClient: OkHttpClient): Builder = apply { this.httpClient = httpClient }

      /** Sets the retry policy applied to transient HTTP failures. */
      fun retryConfig(retryConfig: RetryConfig): Builder = apply { this.retryConfig = retryConfig }

      /**
       * Builds a new [WorkOS] instance using the configured values. Throws
       * [IllegalStateException] if [apiKey] has not been set.
       */
      fun build(): WorkOS {
        val key = apiKey ?: error("apiKey is required")
        return WorkOS(
          apiKey = key,
          clientId = clientId,
          apiBaseUrl = apiBaseUrl,
          httpClient = httpClient ?: defaultHttpClient(),
          retryConfig = retryConfig
        )
      }
    }

    /** Constants and factory helpers for the WorkOS SDK client. */
    companion object {
      /** Default base URL for the WorkOS API. */
      const val DEFAULT_BASE_URL: String = "https://api.workos.com"

      /**
       * Returns a new [Builder] for fluent construction of a [WorkOS] client.
       *
       * Kotlin usage:
       * ```kotlin
       * val workos = WorkOS.builder()
       *   .apiKey("sk_test_xxx")
       *   .build()
       * ```
       *
       * Java usage:
       * ```java
       * WorkOS workos = WorkOS.builder()
       *     .apiKey("sk_test_xxx")
       *     .build();
       * ```
       */
      @JvmStatic
      fun builder(): Builder = Builder()

      private fun defaultHttpClient(): OkHttpClient =
        OkHttpClient
          .Builder()
          .callTimeout(30, java.util.concurrent.TimeUnit.SECONDS)
          .build()

      private fun loadVersion(): String {
        val resource = WorkOS::class.java.getResourceAsStream("/version.properties") ?: return "dev"
        return resource.use { stream ->
          Properties().apply { load(stream) }.getProperty("version", "dev")
        }
      }
    }

    /** Lazily-constructed [AdminPortal] accessor for this [WorkOS] client. */
    val adminPortal: AdminPortal by lazy { AdminPortal(this) }

    /** Lazily-constructed [ApiKeys] accessor for this [WorkOS] client. */
    val apiKeys: ApiKeys by lazy { ApiKeys(this) }

    /** Lazily-constructed [AuditLogs] accessor for this [WorkOS] client. */
    val auditLogs: AuditLogs by lazy { AuditLogs(this) }

    /** Lazily-constructed [Authorization] accessor for this [WorkOS] client. */
    val authorization: Authorization by lazy { Authorization(this) }

    /** Lazily-constructed [Connect] accessor for this [WorkOS] client. */
    val connect: Connect by lazy { Connect(this) }

    /** Lazily-constructed [DirectorySync] accessor for this [WorkOS] client. */
    val directorySync: DirectorySync by lazy { DirectorySync(this) }

    /** Lazily-constructed [Events] accessor for this [WorkOS] client. */
    val events: Events by lazy { Events(this) }

    /** Lazily-constructed [FeatureFlags] accessor for this [WorkOS] client. */
    val featureFlags: FeatureFlags by lazy { FeatureFlags(this) }

    /** Lazily-constructed [MultiFactorAuth] accessor for this [WorkOS] client. */
    val multiFactorAuth: MultiFactorAuth by lazy { MultiFactorAuth(this) }

    /** Lazily-constructed [OrganizationDomains] accessor for this [WorkOS] client. */
    val organizationDomains: OrganizationDomains by lazy { OrganizationDomains(this) }

    /** Lazily-constructed [Organizations] accessor for this [WorkOS] client. */
    val organizations: Organizations by lazy { Organizations(this) }

    /** Lazily-constructed [Pipes] accessor for this [WorkOS] client. */
    val pipes: Pipes by lazy { Pipes(this) }

    /** Lazily-constructed [Radar] accessor for this [WorkOS] client. */
    val radar: Radar by lazy { Radar(this) }

    /** Lazily-constructed [SSO] accessor for this [WorkOS] client. */
    val sso: SSO by lazy { SSO(this) }

    /** Lazily-constructed [UserManagement] accessor for this [WorkOS] client. */
    val userManagement: UserManagement by lazy { UserManagement(this) }

    /** Lazily-constructed [Webhooks] accessor for this [WorkOS] client. */
    val webhooks: Webhooks by lazy { Webhooks(this) }

    /** Lazily-constructed [Widgets] accessor for this [WorkOS] client. */
    val widgets: Widgets by lazy { Widgets(this) }

    /** Lazily-constructed [Groups] accessor for this [WorkOS] client. */
    val groups: Groups by lazy { Groups(this) }

    /** Lazily-constructed [UserManagementOrganizationMembershipGroups] accessor for this [WorkOS] client. */
    val userManagementOrganizationMembershipGroups: UserManagementOrganizationMembershipGroups by lazy {
      UserManagementOrganizationMembershipGroups(this)
    }
  }
