// @oagen-ignore-file
package com.workos

import com.workos.common.http.BaseClient
import com.workos.common.http.RetryConfig
import com.workos.common.json.ObjectMapperFactory
import okhttp3.OkHttpClient
import java.util.Properties
import java.util.concurrent.ConcurrentHashMap
import kotlin.reflect.KClass

/**
 * Top-level WorkOS SDK client.
 *
 * All configuration (API key, base URL, HTTP client, retry settings) is
 * instance-scoped — there is no mutable global state. Service accessors are
 * exposed as Kotlin extension properties on this class from
 * `WorkOS.Generated.kt` (generated by oagen).
 */
open class WorkOS
  @JvmOverloads
  constructor(
    @JvmField val apiKey: String,
    @JvmField val clientId: String? = null,
    apiBaseUrl: String = DEFAULT_BASE_URL,
    @JvmField val httpClient: OkHttpClient = defaultHttpClient(),
    retryConfig: RetryConfig = RetryConfig.DEFAULT
  ) {
    @JvmField
    val apiBaseUrl: String = apiBaseUrl

    @JvmField
    val version: String = loadVersion()

    @JvmField
    val baseClient: BaseClient =
      BaseClient(
        apiKey = apiKey,
        apiBaseUrl = apiBaseUrl,
        httpClient = httpClient,
        objectMapper = ObjectMapperFactory.create(),
        retryConfig = retryConfig,
        userAgent = "workos-kotlin/$version"
      )

    private val serviceCache: ConcurrentHashMap<KClass<*>, Any> = ConcurrentHashMap()

    /** Used by generated service accessors — one instance per service per client. */
    @Suppress("UNCHECKED_CAST")
    fun <T : Any> service(
      cls: KClass<T>,
      factory: () -> T
    ): T = serviceCache.computeIfAbsent(cls) { factory() } as T

    companion object {
      const val DEFAULT_BASE_URL: String = "https://api.workos.com"

      private fun defaultHttpClient(): OkHttpClient =
        OkHttpClient
          .Builder()
          .callTimeout(30, java.util.concurrent.TimeUnit.SECONDS)
          .build()

      private fun loadVersion(): String {
        val resource = WorkOS::class.java.getResourceAsStream("/version.properties") ?: return "dev"
        return resource.use { stream ->
          Properties().apply { load(stream) }.getProperty("version", "dev")
        }
      }
    }
  }
