// This file is auto-generated by oagen. Do not edit.

package com.workos.organizationdomains

import com.workos.WorkOS
import com.workos.common.http.RequestConfig
import com.workos.common.http.RequestOptions
import com.workos.common.http.bodyOf
import com.workos.models.OrganizationDomain
import com.workos.models.OrganizationDomainStandAlone

/** API accessor for OrganizationDomains. */
class OrganizationDomains(
  internal val workos: WorkOS
) {
  /**
   * Create an Organization Domain
   *
   * Creates a new Organization Domain.
   *
   * @param domain The domain to add to the organization.
   * @param organizationId The ID of the organization to add the domain to.
   *
   * @return the OrganizationDomain
   */
  @JvmOverloads
  fun create(
    domain: String,
    organizationId: String,
    requestOptions: RequestOptions? = null
  ): OrganizationDomain {
    val body = bodyOf(
      "domain" to domain,
      "organization_id" to organizationId
    )
    val config =
      RequestConfig(
        method = "POST",
        path = "/organization_domains",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, OrganizationDomain::class.java)
  }

  /**
   * Get an Organization Domain
   *
   * Get the details of an existing organization domain.
   *
   * @param id Unique identifier of the organization domain.
   *
   * @return the OrganizationDomainStandAlone
   */
  @JvmOverloads
  fun get(
    id: String,
    requestOptions: RequestOptions? = null
  ): OrganizationDomainStandAlone {
    val config =
      RequestConfig(
        method = "GET",
        path = "/organization_domains/$id",
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, OrganizationDomainStandAlone::class.java)
  }

  /**
   * Delete an Organization Domain
   *
   * Permanently deletes an organization domain. It cannot be undone.
   *
   * @param id Unique identifier of the organization domain.
   */
  @JvmOverloads
  fun delete(
    id: String,
    requestOptions: RequestOptions? = null
  ) {
    val config =
      RequestConfig(
        method = "DELETE",
        path = "/organization_domains/$id",
        requestOptions = requestOptions
      )
    workos.baseClient.requestVoid(config)
  }

  /**
   * Verify an Organization Domain
   *
   * Initiates verification process for an Organization Domain.
   *
   * @param id Unique identifier of the organization domain.
   *
   * @return the OrganizationDomainStandAlone
   */
  @JvmOverloads
  fun verify(
    id: String,
    requestOptions: RequestOptions? = null
  ): OrganizationDomainStandAlone {
    val body = linkedMapOf<String, Any?>()
    val config =
      RequestConfig(
        method = "POST",
        path = "/organization_domains/$id/verify",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, OrganizationDomainStandAlone::class.java)
  }
}
