// This file is auto-generated by oagen. Do not edit.

package com.workos.auditlogs

import com.fasterxml.jackson.core.type.TypeReference
import com.workos.WorkOS
import com.workos.common.http.Page
import com.workos.common.http.RequestConfig
import com.workos.common.http.RequestOptions
import com.workos.models.AuditLogActionJson
import com.workos.models.AuditLogEvent
import com.workos.models.AuditLogEventCreateResponse
import com.workos.models.AuditLogExportJson
import com.workos.models.AuditLogSchemaActor
import com.workos.models.AuditLogSchemaJson
import com.workos.models.AuditLogSchemaTarget
import com.workos.models.AuditLogsRetentionJson
import com.workos.types.AuditLogsOrder

/** API accessor for AuditLogs. */
class AuditLogs(
  internal val workos: WorkOS
) {
  /** Get Retention */
  @JvmOverloads
  fun getAuditLogsRetention(
    id: String,
    requestOptions: RequestOptions? = null
  ): AuditLogsRetentionJson {
    val params = mutableListOf<Pair<String, String>>()
    val config =
      RequestConfig(
        method = "GET",
        path = "/organizations/$id/audit_logs_retention",
        queryParams = params,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, AuditLogsRetentionJson::class.java)
  }

  /** Set Retention */
  @JvmOverloads
  fun updateAuditLogsRetention(
    id: String,
    retentionPeriodInDays: Long,
    requestOptions: RequestOptions? = null
  ): AuditLogsRetentionJson {
    val params = mutableListOf<Pair<String, String>>()
    val body = linkedMapOf<String, Any?>()
    body["retention_period_in_days"] = retentionPeriodInDays
    val config =
      RequestConfig(
        method = "PUT",
        path = "/organizations/$id/audit_logs_retention",
        queryParams = params,
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, AuditLogsRetentionJson::class.java)
  }

  /** List Actions */
  @JvmOverloads
  fun listActions(
    before: String? = null,
    after: String? = null,
    limit: Long? = null,
    order: AuditLogsOrder? = null,
    requestOptions: RequestOptions? = null
  ): Page<AuditLogActionJson> {
    fun configFor(afterCursor: String? = null): RequestConfig {
      val params = mutableListOf<Pair<String, String>>()
      if (before != null) params += "before" to before.toString()
      if (limit != null) params += "limit" to limit.toString()
      if (order != null) params += "order" to order.value
      val effectiveAfter = afterCursor ?: after
      if (effectiveAfter != null) params += "after" to effectiveAfter
      return RequestConfig(
        method = "GET",
        path = "/audit_logs/actions",
        queryParams = params,
        requestOptions = requestOptions
      )
    }
    val itemType = object : TypeReference<AuditLogActionJson>() {}
    return workos.baseClient.requestPage(configFor(), itemType) { afterCursor -> configFor(afterCursor) }
  }

  /** List Schemas */
  @JvmOverloads
  fun listActionSchemas(
    actionName: String,
    before: String? = null,
    after: String? = null,
    limit: Long? = null,
    order: AuditLogsOrder? = null,
    requestOptions: RequestOptions? = null
  ): Page<AuditLogSchemaJson> {
    fun configFor(afterCursor: String? = null): RequestConfig {
      val params = mutableListOf<Pair<String, String>>()
      if (before != null) params += "before" to before.toString()
      if (limit != null) params += "limit" to limit.toString()
      if (order != null) params += "order" to order.value
      val effectiveAfter = afterCursor ?: after
      if (effectiveAfter != null) params += "after" to effectiveAfter
      return RequestConfig(
        method = "GET",
        path = "/audit_logs/actions/$actionName/schemas",
        queryParams = params,
        requestOptions = requestOptions
      )
    }
    val itemType = object : TypeReference<AuditLogSchemaJson>() {}
    return workos.baseClient.requestPage(configFor(), itemType) { afterCursor -> configFor(afterCursor) }
  }

  /** Create Schema */
  @JvmOverloads
  fun createSchema(
    actionName: String,
    targets: List<AuditLogSchemaTarget>,
    actor: AuditLogSchemaActor? = null,
    metadata: Map<String, Any>? = null,
    requestOptions: RequestOptions? = null
  ): AuditLogSchemaJson {
    val params = mutableListOf<Pair<String, String>>()
    val body = linkedMapOf<String, Any?>()
    body["targets"] = targets
    if (actor != null) body["actor"] = actor
    if (metadata != null) body["metadata"] = metadata
    val config =
      RequestConfig(
        method = "POST",
        path = "/audit_logs/actions/$actionName/schemas",
        queryParams = params,
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, AuditLogSchemaJson::class.java)
  }

  /** Create Event */
  @JvmOverloads
  fun createEvent(
    organizationId: String,
    event: AuditLogEvent,
    requestOptions: RequestOptions? = null
  ): AuditLogEventCreateResponse {
    val params = mutableListOf<Pair<String, String>>()
    val body = linkedMapOf<String, Any?>()
    body["organization_id"] = organizationId
    body["event"] = event
    val config =
      RequestConfig(
        method = "POST",
        path = "/audit_logs/events",
        queryParams = params,
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, AuditLogEventCreateResponse::class.java)
  }

  /** Create Export */
  @JvmOverloads
  fun createExport(
    organizationId: String,
    rangeStart: String,
    rangeEnd: String,
    actions: List<String>? = null,
    actors: List<String>? = null,
    actorNames: List<String>? = null,
    actorIds: List<String>? = null,
    targets: List<String>? = null,
    requestOptions: RequestOptions? = null
  ): AuditLogExportJson {
    val params = mutableListOf<Pair<String, String>>()
    val body = linkedMapOf<String, Any?>()
    body["organization_id"] = organizationId
    body["range_start"] = rangeStart
    body["range_end"] = rangeEnd
    if (actions != null) body["actions"] = actions
    if (actors != null) body["actors"] = actors
    if (actorNames != null) body["actor_names"] = actorNames
    if (actorIds != null) body["actor_ids"] = actorIds
    if (targets != null) body["targets"] = targets
    val config =
      RequestConfig(
        method = "POST",
        path = "/audit_logs/exports",
        queryParams = params,
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, AuditLogExportJson::class.java)
  }

  /** Get Export */
  @JvmOverloads
  fun getExport(
    auditLogExportId: String,
    requestOptions: RequestOptions? = null
  ): AuditLogExportJson {
    val params = mutableListOf<Pair<String, String>>()
    val config =
      RequestConfig(
        method = "GET",
        path = "/audit_logs/exports/$auditLogExportId",
        queryParams = params,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, AuditLogExportJson::class.java)
  }
}
