// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** AccountSelectionRequiredError model. */
data class AccountSelectionRequiredError(
  /** A human-readable explanation of the ambiguity. */
  @JsonProperty("message")
  val message: String,

  /** Indicates that several connected accounts match and the request must name one. */
  @JsonProperty("code")
  val code: String = "account_selection_required"
)
