// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** The user to attach to the claim attempt, identified by email and external ID. */
data class AgentAdminLinkClaimAttemptToExternalUserRequestUser(
  /** The email address of the user. */
  @JsonProperty("email")
  val email: String,

  /** The external ID of the user. */
  @JsonProperty("external_id")
  val externalId: String
)
