// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** Token and session lifetimes for sessions minted from this blueprint. */
data class AgentBlueprintSessionSetting(
  /** Maximum lifetime of a session in seconds; refreshes never extend a session past this. */
  @JsonProperty("max_age_seconds")
  val maxAgeSeconds: Long,

  /** Lifetime of each minted access token in seconds. */
  @JsonProperty("access_token_ttl_seconds")
  val accessTokenTtlSeconds: Long,

  /** Lifetime of each rotated refresh token in seconds. */
  @JsonProperty("refresh_token_ttl_seconds")
  val refreshTokenTtlSeconds: Long
)
