// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** The event payload. */
data class AgentBlueprintCreatedData(
  /** Unique identifier of the agent blueprint. */
  @JsonProperty("id")
  val id: String,

  /** Human-readable name of the agent blueprint. */
  @JsonProperty("name")
  val name: String,

  /** Human-readable description of the agent blueprint. */
  @JsonProperty("description")
  val description: String?,

  /** Permission slugs forming the ceiling on what sessions minted from this blueprint may do. */
  @JsonProperty("permissions")
  val permissions: List<String>,

  /** Who may mint sessions from this blueprint. */
  @JsonProperty("invocable_by")
  val invocableBy: AgentBlueprintCreatedDataInvocableBy,

  /** Token and session lifetimes for sessions minted from this blueprint. */
  @JsonProperty("session_settings")
  val sessionSettings: AgentBlueprintCreatedDataSessionSetting,

  /** The timestamp when the agent blueprint was created. */
  @JsonProperty("created_at")
  val createdAt: String,

  /** The timestamp when the agent blueprint was last updated. */
  @JsonProperty("updated_at")
  val updatedAt: String,

  /** Distinguishes the agent blueprint object. */
  @JsonProperty("object")
  val objectType: String = "agent_blueprint"
)
