// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** The event payload. */
data class AgentRegistrationDeletedData(
  /** The agent registration that was deleted. */
  @JsonProperty("agent_registration_id")
  val agentRegistrationId: String
)
