// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import java.time.OffsetDateTime

/** The agent identity associated with this registration. */
data class AgentRegistrationAgentIdentity(
  /** Unique identifier of the agent identity. */
  @JsonProperty("id")
  val id: String,

  /** Identifier of the AuthKit user the agent identity is bound to, or `null` when the agent is not associated with a user. */
  @JsonProperty("userland_user_id")
  val userlandUserId: String?,

  /** The timestamp when the agent identity was created. */
  @JsonProperty("created_at")
  val createdAt: OffsetDateTime,

  /** The timestamp when the agent identity was last updated. */
  @JsonProperty("updated_at")
  val updatedAt: OffsetDateTime
)
