// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import java.time.OffsetDateTime

/** Previous API key attributes before the update. */
data class ApiKeyUpdatedDataPreviousAttribute(
  /** The previous timestamp when the API Key expired. Null means the key did not expire. */
  @JsonProperty("expires_at")
  val expiresAt: OffsetDateTime?
)
