// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** ApiKeyOwner model. */
data class ApiKeyOwner(
  /** Unique identifier of the API Key owner. */
  @JsonProperty("id")
  val id: String,
  /** The type of the API Key owner. */
  @JsonProperty("type")
  val type: String = "organization"
)
