// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** ApiKeyValidationResponse model. */
data class ApiKeyValidationResponse(
  /** The api key. */
  @JsonProperty("api_key")
  val apiKey: ApiKey?
)
