// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import com.workos.types.AuditLogExportState
import java.time.OffsetDateTime

/** AuditLogExport model. */
data class AuditLogExport(
  /** The unique ID of the Audit Log Export. */
  @JsonProperty("id")
  val id: String,

  /** The state of the export. Possible values: pending, ready, error, expired. */
  @JsonProperty("state")
  val state: AuditLogExportState,

  /** An ISO 8601 timestamp. */
  @JsonProperty("created_at")
  val createdAt: OffsetDateTime,

  /** An ISO 8601 timestamp. */
  @JsonProperty("updated_at")
  val updatedAt: OffsetDateTime,

  /** Distinguishes the Audit Log Export object. */
  @JsonProperty("object")
  val objectType: String = "audit_log_export",

  /** A URL to the CSV file. Only defined when the Audit Log Export is ready. */
  @JsonProperty("url")
  val url: String? = null
)
