// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import java.time.OffsetDateTime

/** AuditLogEvent model. */
data class AuditLogEvent(
  /** Identifier of what happened. */
  @JvmField
  @JsonProperty("action")
  val action: String,
  /** ISO-8601 value of when the action occurred. */
  @JvmField
  @JsonProperty("occurred_at")
  val occurredAt: OffsetDateTime,
  /** The entity that performed the action. */
  @JvmField
  @JsonProperty("actor")
  val actor: AuditLogEventActor,
  /** The resources affected by the action. */
  @JvmField
  @JsonProperty("targets")
  val targets: List<AuditLogEventTarget>,
  /** Additional context about where and how the action occurred. */
  @JvmField
  @JsonProperty("context")
  val context: AuditLogEventContext,
  /** Additional data associated with the event or entity. */
  @JvmField
  @JsonProperty("metadata")
  val metadata: Map<String, Any>? = null,
  /** What schema version the event is associated with. */
  @JvmField
  @JsonProperty("version")
  val version: Long? = null
)
