// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** Details about the authentication error. */
data class AuthenticationMfaFailedDataError(
  /** The error code. */
  @JsonProperty("code")
  val code: String,
  /** A human-readable error message. */
  @JsonProperty("message")
  val message: String
)
