// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** AuthorizationCheck model. */
data class AuthorizationCheck(
  /** Whether the organization membership has the specified permission on the resource. */
  @JvmField
  @JsonProperty("authorized")
  val authorized: Boolean
)
