// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** The event payload. */
data class AuthenticationMfaFailedData(
  /** The IP address of the request. */
  @JsonProperty("ip_address")
  val ipAddress: String?,
  /** The user agent of the request. */
  @JsonProperty("user_agent")
  val userAgent: String?,
  /** The ID of the user. */
  @JsonProperty("user_id")
  val userId: String?,
  /** The email address of the user. */
  @JsonProperty("email")
  val email: String?,
  /** Details about the authentication error. */
  @JsonProperty("error")
  val error: AuthenticationMfaFailedDataError,
  /** Always `"mfa"`. */
  @JsonProperty("type")
  val type: String = "mfa",
  /** Always `"failed"`. */
  @JsonProperty("status")
  val status: String = "failed"
)
