// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** AuthMethodMismatchError model. */
data class AuthMethodMismatchError(
  /** A human-readable explanation of the mismatch. */
  @JsonProperty("message")
  val message: String,

  /** Error code indicating the endpoint does not match the installation auth method. */
  @JsonProperty("code")
  val code: String = "auth_method_mismatch"
)
