// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** AuthkitOAuthResource model. */
data class AuthkitOAuthResource(
  /** The ID of the MCP resource indicator. */
  @JsonProperty("id")
  val id: String,

  /** The resource URI. */
  @JsonProperty("uri")
  val uri: String,

  /** Whether this is the default MCP resource indicator for the environment. */
  @JsonProperty("default")
  val default: Boolean,

  /** The timestamp when the MCP resource indicator was created. */
  @JsonProperty("created_at")
  val createdAt: String,

  /** The timestamp when the MCP resource indicator was last updated. */
  @JsonProperty("updated_at")
  val updatedAt: String,

  /** The object type. */
  @JsonProperty("object")
  val objectType: String = "authkit_oauth_resource"
)
