// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import com.workos.types.ConnectedAccountAuthMethod
import com.workos.types.ConnectedAccountConnectionRole
import com.workos.types.ConnectedAccountState

/** ConnectedAccount model. */
data class ConnectedAccount(
  /** The unique identifier of the connected account. */
  @JsonProperty("id")
  val id: String,

  /** Whether this row is the compatibility connection visible to undeclared clients or a standard peer for plural-aware clients. The role does not indicate preference or creation order. */
  @JsonProperty("connection_role")
  val connectionRole: ConnectedAccountConnectionRole,

  /** A best-effort identifier for the provider account this connection points at. It is correlation metadata, not the connection identifier or a selector. */
  @JsonProperty("account_identifier")
  val accountIdentifier: String?,

  /** A mutable, non-unique display name for the provider account connection. */
  @JsonProperty("account_display_name")
  val accountDisplayName: String?,

  /** The [User](https://workos.com/docs/reference/authkit/user) identifier associated with this connection. */
  @JsonProperty("user_id")
  val userId: String?,

  /** The [Organization](https://workos.com/docs/reference/organization) identifier associated with this connection, or `null` if not scoped to an organization. */
  @JsonProperty("organization_id")
  val organizationId: String?,

  /** The OAuth scopes granted for this connection. */
  @JsonProperty("scopes")
  val scopes: List<String>,

  /** The state of the connected account: */
  @JsonProperty("state")
  val state: ConnectedAccountState,

  /** The timestamp when the connection was created. */
  @JsonProperty("created_at")
  val createdAt: String,

  /** The timestamp when the connection was last updated. */
  @JsonProperty("updated_at")
  val updatedAt: String,

  /** Distinguishes the connected account object. */
  @JsonProperty("object")
  val objectType: String = "connected_account",

  /** The authentication method used for this connection (`oauth`, `api_key`, or `client_credentials`). Defaults to `oauth` if absent. */
  @JsonProperty("auth_method")
  val authMethod: ConnectedAccountAuthMethod? = null,

  /** The last four characters of the API key, or `null` for OAuth connections. */
  @JsonProperty("api_key_last_4")
  val apiKeyLast4: String? = null,

  /** The client ID supplied for this connection. Only present when `auth_method` is `client_credentials`. */
  @JsonProperty("client_id")
  val clientId: String? = null,

  /** The last four characters of the client secret supplied for this connection, or `null` when it can't be read. Only present when `auth_method` is `client_credentials`. */
  @JsonProperty("client_secret_last_4")
  val clientSecretLast4: String? = null,

  /** The connection-level configuration values stored for this connection — the fields the provider declares at `installation` scope, excluding any it declares as secret. Only present when `auth_method` is `client_credentials`. */
  @JsonProperty("config")
  val config: Map<String, String>? = null
)
