// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** ConnectionDomain model. */
data class ConnectionDomain(
  /** Unique identifier for the Connection Domain. */
  @JvmField
  @JsonProperty("id")
  val id: String,
  /** The domain value. */
  @JvmField
  @JsonProperty("domain")
  val domain: String,
  /** Distinguishes the Connection Domain object. */
  @JvmField
  @JsonProperty("object")
  val `object`: String = "connection_domain"
)
