// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** ConnectApplicationRedirectUri model. */
data class ConnectApplicationRedirectUri(
  /** The redirect URI for the application. */
  @JsonProperty("uri")
  val uri: String,
  /** Whether this is the default redirect URI. */
  @JsonProperty("default")
  val default: Boolean
)
