// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import com.workos.types.ConnectionState
import com.workos.types.ConnectionStatus
import com.workos.types.ConnectionType
import java.time.OffsetDateTime

/** Connection model. */
data class Connection(
  /** Unique identifier for the Connection. */
  @JsonProperty("id")
  val id: String,

  /** The type of the SSO Connection used to authenticate the user. The Connection type may be used to dynamically generate authorization URLs. */
  @JsonProperty("connection_type")
  val connectionType: ConnectionType,

  /** A human-readable name for the Connection. This will most commonly be the organization's name. */
  @JsonProperty("name")
  val name: String,

  /** Indicates whether a Connection is able to authenticate users. */
  @JsonProperty("state")
  val state: ConnectionState,

  /** Deprecated. Use `state` instead. */
  @JsonProperty("status")
  @Deprecated("Deprecated. Use `state` instead.")
  val status: ConnectionStatus,

  /** List of Organization Domains. */
  @JsonProperty("domains")
  val domains: List<ConnectionDomain>,

  /** An ISO 8601 timestamp. */
  @JsonProperty("created_at")
  val createdAt: OffsetDateTime,

  /** An ISO 8601 timestamp. */
  @JsonProperty("updated_at")
  val updatedAt: OffsetDateTime,

  /** Distinguishes the Connection object. */
  @JsonProperty("object")
  val objectType: String = "connection",

  /** Unique identifier for the Organization in which the Connection resides. */
  @JsonProperty("organization_id")
  val organizationId: String? = null,

  /** The immutable callback endpoint for this Connection. For SAML connections this is the ACS URL; for OIDC connections this is the redirect URI. */
  @JsonProperty("callback_endpoint")
  val callbackEndpoint: String? = null
)
