// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import java.time.OffsetDateTime

/** ConnectApplication model. */
data class ConnectApplication(
  /** The unique ID of the connect application. */
  @JsonProperty("id")
  val id: String,
  /** The client ID of the connect application. */
  @JsonProperty("client_id")
  val clientId: String,
  /** A description of the connect application. */
  @JsonProperty("description")
  val description: String?,
  /** The name of the connect application. */
  @JsonProperty("name")
  val name: String,
  /** The scopes available for this application. */
  @JsonProperty("scopes")
  val scopes: List<String>,
  /** An ISO 8601 timestamp. */
  @JsonProperty("created_at")
  val createdAt: OffsetDateTime,
  /** An ISO 8601 timestamp. */
  @JsonProperty("updated_at")
  val updatedAt: OffsetDateTime,
  /** Distinguishes the connect application object. */
  @JsonProperty("object")
  val objectType: String = "connect_application",
  /** The type of the application. */
  @JsonProperty("application_type")
  val applicationType: String = "m2m",
  /** The ID of the organization the application belongs to. */
  @JsonProperty("organization_id")
  val organizationId: String? = null,
  /** The redirect URIs configured for this application. */
  @JsonProperty("redirect_uris")
  val redirectUris: List<ConnectApplicationRedirectUri>? = null,
  /** Whether the application uses PKCE for authorization. */
  @JsonProperty("uses_pkce")
  val usesPkce: Boolean? = null,
  /** Whether the application is a first-party application. */
  @JsonProperty("is_first_party")
  val isFirstParty: Boolean = true,
  /** Whether the application was dynamically registered. */
  @JsonProperty("was_dynamically_registered")
  val wasDynamicallyRegistered: Boolean = false
)
