// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import com.workos.types.ConnectionSAMLCertificateRenewedDataCertificateCertificateType
import java.time.OffsetDateTime

/** The renewed SAML certificate details. */
data class ConnectionSAMLCertificateRenewedDataCertificate(
  /** The type of the SAML certificate. */
  @JsonProperty("certificate_type")
  val certificateType: ConnectionSAMLCertificateRenewedDataCertificateCertificateType,
  /** An ISO 8601 timestamp. */
  @JsonProperty("expiry_date")
  val expiryDate: OffsetDateTime
)
