// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** CreateRedirectUri model. */
data class CreateRedirectUri(
  /** The redirect URI to create. */
  @JsonProperty("uri")
  val uri: String
)
