// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** CreateGroupMembership model. */
data class CreateGroupMembership(
  /** The ID of the Organization Membership to add to the group. */
  @JsonProperty("organization_membership_id")
  val organizationMembershipId: String
)
