// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** CreateConnectionSAMLOptions model. */
data class CreateConnectionSAMLOptions(
  /** The Identity Provider metadata URL. When provided, the IdP fields and signing certificates are imported from the metadata document. Mutually exclusive with the manual IdP fields. */
  @JsonProperty("idp_metadata_url")
  val idpMetadataUrl: String? = null,

  /** A custom Assertion Consumer Service (ACS) URL override. When omitted, the standard WorkOS-generated ACS URL is used. */
  @JsonProperty("acs_url")
  val acsUrl: String? = null,

  /** A custom Service Provider Entity ID (audience) override. When omitted, the connection external key is used. */
  @JsonProperty("sp_entity_id")
  val spEntityId: String? = null,

  /** The Identity Provider Entity ID. */
  @JsonProperty("idp_entity_id")
  val idpEntityId: String? = null,

  /** The Identity Provider SSO URL. Required when configuring the connection with manual IdP fields. */
  @JsonProperty("idp_sso_url")
  val idpSSOUrl: String? = null,

  /** The X.509 certificates used to verify signed SAML responses from the Identity Provider. Required when configuring the connection with manual IdP fields. */
  @JsonProperty("idp_signing_certs")
  val idpSigningCerts: List<String>? = null,

  /** The customer-owned key pair used to sign SAML requests sent to the Identity Provider. When omitted, WorkOS generates and manages the signing key pair. */
  @JsonProperty("sp_signing_key_pair")
  val spSigningKeyPair: CreateConnectionKeyPair? = null,

  /** The customer-owned key pairs used to decrypt encrypted SAML responses from the Identity Provider. When omitted, WorkOS generates and manages the encryption key pair. */
  @JsonProperty("sp_encryption_key_pairs")
  val spEncryptionKeyPairs: List<CreateConnectionKeyPair>? = null
)
