// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** CreateAuthkitOAuthResource model. */
data class CreateAuthkitOAuthResource(
  /** The resource URI. May be a wildcard pattern with a single `*` in the leftmost hostname label, where enabled for the environment. */
  @JsonProperty("uri")
  val uri: String,

  /** Whether the resource being created becomes the environment default, clearing any previous default. Applies at creation only — this API has no update endpoint yet, so changing the default on an existing resource is done from the dashboard. A wildcard pattern cannot be the default. */
  @JsonProperty("default")
  val default: Boolean? = null
)
