// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** CreatePasswordReset model. */
data class CreatePasswordReset(
  /** The password reset token. */
  @JsonProperty("token")
  val token: String,
  /** The new password to set for the user. */
  @JsonProperty("new_password")
  val newPassword: String
)
