// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** CreateUserOrganizationMembership model. */
data class CreateUserOrganizationMembership(
  /** The ID of the [user](https://workos.com/docs/reference/authkit/user). */
  @JsonProperty("user_id")
  val userId: String,
  /** The ID of the [organization](https://workos.com/docs/reference/organization) which the user belongs to. */
  @JsonProperty("organization_id")
  val organizationId: String,
  /** A single role identifier. Defaults to `member` or the explicit default role. Mutually exclusive with `role_slugs`. */
  @JsonProperty("role_slug")
  val roleSlug: String? = null,
  /** An array of role identifiers. Limited to one role when Multiple Roles is disabled. Mutually exclusive with `role_slug`. */
  @JsonProperty("role_slugs")
  val roleSlugs: List<String>? = null
)
