// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** CreateAuthorizationPermission model. */
data class CreateAuthorizationPermission(
  /** A unique key to reference the permission. Must be lowercase and contain only letters, numbers, hyphens, underscores, colons, periods, and asterisks. */
  @JvmField
  @JsonProperty("slug")
  val slug: String,
  /** A descriptive name for the Permission. */
  @JvmField
  @JsonProperty("name")
  val name: String,
  /** An optional description of the Permission. */
  @JvmField
  @JsonProperty("description")
  val description: String? = null,
  /** The slug of the resource type this permission is scoped to. */
  @JvmField
  @JsonProperty("resource_type_slug")
  val resourceTypeSlug: String? = null
)
