// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** CreateGroup model. */
data class CreateGroup(
  /** The name of the Group. */
  @JsonProperty("name")
  val name: String,
  /** An optional description of the Group. */
  @JsonProperty("description")
  val description: String? = null
)
