// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** DataIntegrationConfigurationListResponse model. */
data class DataIntegrationConfigurationListResponse(
  /** A list of data integration configurations for the organization. */
  @JsonProperty("data")
  val data: List<DataIntegrationConfigurationResponse>,

  /** Indicates this is a list response. */
  @JsonProperty("object")
  val objectType: String = "list"
)
