// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** DataIntegrationsUpsertApiKeyRequest model. */
data class DataIntegrationsUpsertApiKeyRequest(
  /** A [User](https://workos.com/docs/reference/authkit/user) identifier. */
  @JsonProperty("user_id")
  val userId: String,

  /** The API key secret to store for this integration. */
  @JsonProperty("secret")
  val secret: String,

  /** An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization. */
  @JsonProperty("organization_id")
  val organizationId: String? = null
)
