// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import com.workos.types.DataIntegrationsListResponseDataOwnership

/** DataIntegrationsListResponseData model. */
data class DataIntegrationsListResponseData(
  /** The unique identifier of the provider. */
  @JsonProperty("id")
  val id: String,
  /** The display name of the provider (e.g., "GitHub", "Slack"). */
  @JsonProperty("name")
  val name: String,
  /** A description of the provider explaining how it will be used, if configured. */
  @JsonProperty("description")
  val description: String?,
  /** The slug identifier used in API calls (e.g., `github`, `slack`, `notion`). */
  @JsonProperty("slug")
  val slug: String,
  /** The type of integration (e.g., `github`, `slack`). */
  @JsonProperty("integration_type")
  val integrationType: String,
  /** The type of credentials used by the provider (e.g., `oauth2`). */
  @JsonProperty("credentials_type")
  val credentialsType: String,
  /** The OAuth scopes configured for this provider, or `null` if none are configured. */
  @JsonProperty("scopes")
  val scopes: List<String>?,
  /** Whether the provider is owned by a user or organization. */
  @JsonProperty("ownership")
  val ownership: DataIntegrationsListResponseDataOwnership,
  /** The timestamp when the provider was created. */
  @JsonProperty("created_at")
  val createdAt: String,
  /** The timestamp when the provider was last updated. */
  @JsonProperty("updated_at")
  val updatedAt: String,
  /** The user's [connected account](https://workos.com/docs/reference/pipes/connected-account) for this provider, or `null` if the user has not connected. */
  @JsonProperty("connected_account")
  val connectedAccount: DataIntegrationsListResponseDataConnectedAccount?,
  /** Distinguishes the data provider object. */
  @JsonProperty("object")
  val objectType: String = "data_provider"
)
