// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import com.workos.types.DataIntegrationCredentialsResponseError

/** DataIntegrationCredentialsResponse model. */
data class DataIntegrationCredentialsResponse(
  /** Indicates credentials are available. */
  @JsonProperty("active")
  val active: Boolean? = null,

  /** The credential object containing the vended secret. */
  @JsonProperty("credential")
  val credential: DataIntegrationCredentialsResponseCredential? = null,

  /** The reason credentials are unavailable. Additional values may be added in the future; handle unknown values gracefully. */
  @JsonProperty("error")
  val error: DataIntegrationCredentialsResponseError? = null
)
