// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** DeviceAuthorizationResponse model. */
data class DeviceAuthorizationResponse(
  /** The device verification code. */
  @JsonProperty("device_code")
  val deviceCode: String,
  /** The end-user verification code. */
  @JsonProperty("user_code")
  val userCode: String,
  /** The end-user verification URI. */
  @JsonProperty("verification_uri")
  val verificationUri: String,
  /** Lifetime in seconds of the codes. */
  @JsonProperty("expires_in")
  val expiresIn: Double,
  /** Verification URI that includes the user code. */
  @JsonProperty("verification_uri_complete")
  val verificationUriComplete: String? = null,
  /** Minimum polling interval in seconds. */
  @JsonProperty("interval")
  val interval: Double? = null
)
