// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import com.workos.types.DsyncDeactivatedDataState
import com.workos.types.DsyncDeactivatedDataType
import java.time.OffsetDateTime

/** The event payload. */
data class DsyncDeactivatedData(
  /** Distinguishes the directory object. */
  @JvmField
  @JsonProperty("object")
  val `object`: String,
  /** Unique identifier of the directory. */
  @JvmField
  @JsonProperty("id")
  val id: String,
  /** The type of the directory. */
  @JvmField
  @JsonProperty("type")
  val type: DsyncDeactivatedDataType,
  /** The current state of the directory. */
  @JvmField
  @JsonProperty("state")
  val state: DsyncDeactivatedDataState,
  /** The name of the directory. */
  @JvmField
  @JsonProperty("name")
  val name: String,
  /** An ISO 8601 timestamp. */
  @JvmField
  @JsonProperty("created_at")
  val createdAt: OffsetDateTime,
  /** An ISO 8601 timestamp. */
  @JvmField
  @JsonProperty("updated_at")
  val updatedAt: OffsetDateTime,
  /** The external key of the directory. */
  @JvmField
  @JsonProperty("external_key")
  val externalKey: String,
  /** The domains associated with the directory. */
  @JvmField
  @JsonProperty("domains")
  val domains: List<DsyncDeactivatedDataDomain>,
  /** The ID of the organization the directory belongs to. */
  @JvmField
  @JsonProperty("organization_id")
  val organizationId: String? = null
)
