// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** EventContextGoogleAnalyticsSession model. */
data class EventContextGoogleAnalyticsSession(
  /** The Google Analytics container ID. */
  @JvmField
  @JsonProperty("containerId")
  val containerId: String,
  /** The Google Analytics session ID. */
  @JvmField
  @JsonProperty("sessionId")
  val sessionId: String? = null,
  /** The Google Analytics session number. */
  @JvmField
  @JsonProperty("sessionNumber")
  val sessionNumber: String? = null
)
