// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** Additional context about the event. */
data class EventContext(
  /** The Google Analytics client ID. */
  @JsonProperty("google_analytics_client_id")
  val googleAnalyticsClientId: String? = null,
  /** The Google Analytics sessions associated with the event. */
  @JsonProperty("google_analytics_sessions")
  val googleAnalyticsSessions: List<EventContextGoogleAnalyticsSession>? = null,
  /** The anonymous ID from analytics. */
  @JsonProperty("ajs_anonymous_id")
  val ajsAnonymousId: String? = null,
  /** The client ID associated with the event. */
  @JsonProperty("client_id")
  val clientId: String? = null,
  @JsonProperty("actor")
  val actor: EventContextActor? = null,
  /** Attributes that changed from their previous values. */
  @JsonProperty("previous_attributes")
  val previousAttributes: Map<String, Any>? = null
)
