// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import java.time.OffsetDateTime

/** The event payload. */
data class FlagRuleUpdatedData(
  /** Unique identifier of the Feature Flag. */
  @JvmField
  @JsonProperty("id")
  val id: String,
  /** The ID of the environment the Feature Flag belongs to. */
  @JvmField
  @JsonProperty("environment_id")
  val environmentId: String,
  /** A unique key to reference the Feature Flag. */
  @JvmField
  @JsonProperty("slug")
  val slug: String,
  /** A descriptive name for the Feature Flag. */
  @JvmField
  @JsonProperty("name")
  val name: String,
  /** A description for the Feature Flag. */
  @JvmField
  @JsonProperty("description")
  val description: String?,
  /** The owner of the Feature Flag. */
  @JvmField
  @JsonProperty("owner")
  val owner: FlagRuleUpdatedDataOwner?,
  /** Labels assigned to the Feature Flag for categorizing and filtering. */
  @JvmField
  @JsonProperty("tags")
  val tags: List<String>,
  /** Specifies whether the Feature Flag is active for the current environment. */
  @JvmField
  @JsonProperty("enabled")
  val enabled: Boolean,
  /** The value returned for users and organizations who don't match any configured targeting rules. */
  @JvmField
  @JsonProperty("default_value")
  val defaultValue: Boolean,
  /** An ISO 8601 timestamp. */
  @JvmField
  @JsonProperty("created_at")
  val createdAt: OffsetDateTime,
  /** An ISO 8601 timestamp. */
  @JvmField
  @JsonProperty("updated_at")
  val updatedAt: OffsetDateTime,
  /** Always `"feature_flag"`. */
  @JvmField
  @JsonProperty("object")
  val `object`: String = "feature_flag"
)
