// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** Attributes that changed from their previous values. */
data class FlagUpdatedContextPreviousAttribute(
  /** The previous data attributes of the flag. */
  @JsonProperty("data")
  val data: FlagUpdatedContextPreviousAttributeData? = null
)
