// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import java.time.OffsetDateTime

/** FlagUpdated model. */
data class FlagUpdated(
  /** Unique identifier for the event. */
  @JsonProperty("id")
  override val id: String,
  /** The event payload. */
  @JsonProperty("data")
  val data: FlagUpdatedData,
  /** An ISO 8601 timestamp. */
  @JsonProperty("created_at")
  override val createdAt: OffsetDateTime,
  /** Additional context about the event. */
  @JsonProperty("context")
  val context: FlagUpdatedContext,
  /** Always `"flag.updated"`. */
  @JsonProperty("event")
  override val event: String = "flag.updated",
  /** Distinguishes the Event object. */
  @JsonProperty("object")
  val objectType: String = "event"
) : WorkOSEvent
