// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import java.time.OffsetDateTime

/** GroupRoleAssignment model. */
data class GroupRoleAssignment(
  /** Unique identifier of the group role assignment. */
  @JsonProperty("id")
  val id: String,

  /** The ID of the group the role is assigned to. */
  @JsonProperty("group_id")
  val groupId: String,

  /** The role included in the assignment. */
  @JsonProperty("role")
  val role: SlimRole,

  /** The resource the role is assigned on. */
  @JsonProperty("resource")
  val resource: GroupRoleAssignmentResource,

  /** An ISO 8601 timestamp. */
  @JsonProperty("created_at")
  val createdAt: OffsetDateTime,

  /** An ISO 8601 timestamp. */
  @JsonProperty("updated_at")
  val updatedAt: OffsetDateTime,

  /** Distinguishes the group role assignment object. */
  @JsonProperty("object")
  val objectType: String = "group_role_assignment"
)
