// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** IntentOptions model. */
data class IntentOptions(
  /** SSO-specific options for the Admin Portal. */
  @JvmField
  @JsonProperty("sso")
  val sso: SSOIntentOptions
)
