// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** JwksResponse model. */
data class JwksResponse(
  /** The public keys used for verifying access tokens. */
  @JvmField
  @JsonProperty("keys")
  val keys: List<JwksResponseKeys>
)
