// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import java.time.OffsetDateTime

/** MagicAuth model. */
data class MagicAuth(
  /** Distinguishes the Magic Auth object. */
  @JvmField
  @JsonProperty("object")
  val `object`: String,
  /** The unique ID of the Magic Auth code. */
  @JvmField
  @JsonProperty("id")
  val id: String,
  /** The unique ID of the user. */
  @JvmField
  @JsonProperty("user_id")
  val userId: String,
  /** The email address of the user. */
  @JvmField
  @JsonProperty("email")
  val email: String,
  /** The timestamp when the Magic Auth code expires. */
  @JvmField
  @JsonProperty("expires_at")
  val expiresAt: OffsetDateTime,
  /** An ISO 8601 timestamp. */
  @JvmField
  @JsonProperty("created_at")
  val createdAt: OffsetDateTime,
  /** An ISO 8601 timestamp. */
  @JvmField
  @JsonProperty("updated_at")
  val updatedAt: OffsetDateTime,
  /** The code used to verify the Magic Auth code. */
  @JvmField
  @JsonProperty("code")
  val code: String
)
