// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import com.workos.types.OrganizationConnectedAccountState
import java.time.OffsetDateTime

/** OrganizationConnectedAccount model. */
data class OrganizationConnectedAccount(
  /** The [User](https://workos.com/docs/reference/authkit/user) identifier of the organization member on whose behalf the connected account is being imported or updated. The user must be an active member of the organization. */
  @JsonProperty("user_id")
  val userId: String,

  /** The OAuth access token for the connected account. */
  @JsonProperty("access_token")
  val accessToken: String? = null,

  /** The OAuth refresh token for the connected account. */
  @JsonProperty("refresh_token")
  val refreshToken: String? = null,

  /** The ISO-8601 timestamp when the access token expires. Required when `access_token` is provided for tokens that expire. */
  @JsonProperty("expires_at")
  val expiresAt: OffsetDateTime? = null,

  /** The OAuth scopes granted for this connection. */
  @JsonProperty("scopes")
  val scopes: List<String>? = null,

  /** Explicitly set the state of the connected account. When omitted, the state is derived from the token combination provided. */
  @JsonProperty("state")
  val state: OrganizationConnectedAccountState? = null
)
