// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** PatchConnectionAttributeMaps model. */
data class PatchConnectionAttributeMaps(
  /** How IdP attributes or claims map onto the standard WorkOS profile fields. Only the provided fields are updated. */
  @JsonProperty("standard_attributes")
  val standardAttributes: PatchConnectionStandardAttributes? = null,

  /** How IdP attributes or claims map onto custom attributes, keyed by custom attribute name. Custom attributes must already be defined in the WorkOS dashboard. Only the provided keys are updated; a `null` value unsets that mapping. */
  @JsonProperty("custom_attributes")
  val customAttributes: Map<String, String?>? = null
)
