// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** PatchConnection model. */
data class PatchConnection(
  /** A human-readable name for the Connection. */
  @JsonProperty("name")
  val name: String? = null,

  /** The customer-owned identifier for the Connection. Set to `null` to stop tracking one. */
  @JsonProperty("external_id")
  val externalId: String? = null,

  /** The type of the Connection. Immutable after creation — it may be sent, but only with the Connection current type. */
  @JsonProperty("connection_type")
  val connectionType: String? = null,

  /** How IdP attributes or claims map onto WorkOS profile fields. Only the provided fields are updated. */
  @JsonProperty("attribute_maps")
  val attributeMaps: PatchConnectionAttributeMaps? = null,

  /** Protocol configuration for SAML connections. Only the provided fields are updated. Mutually exclusive with `oidc_options`. */
  @JsonProperty("saml_options")
  val samlOptions: PatchConnectionSAMLOptions? = null,

  /** Protocol configuration for OIDC connections. Only the provided fields are updated. Mutually exclusive with `saml_options`. */
  @JsonProperty("oidc_options")
  val oidcOptions: PatchConnectionOidcOptions? = null
)
