// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import com.workos.types.ProfileConnectionType

/** Profile model. */
data class Profile(
  /** Unique identifier of the profile. */
  @JsonProperty("id")
  val id: String,
  /** The ID of the organization the user belongs to. */
  @JsonProperty("organization_id")
  val organizationId: String?,
  /** The ID of the SSO connection used for authentication. */
  @JsonProperty("connection_id")
  val connectionId: String,
  /** The type of SSO connection. */
  @JsonProperty("connection_type")
  val connectionType: ProfileConnectionType,
  /** The user's unique identifier from the identity provider. */
  @JsonProperty("idp_id")
  val idpId: String,
  /** The user's email address. */
  @JsonProperty("email")
  val email: String,
  /** The user's first name. */
  @JsonProperty("first_name")
  val firstName: String?,
  /** The user's last name. */
  @JsonProperty("last_name")
  val lastName: String?,
  /** The complete set of raw attributes returned by the identity provider. */
  @JsonProperty("raw_attributes")
  val rawAttributes: Map<String, Any>,
  /** Distinguishes the profile object. */
  @JsonProperty("object")
  val objectType: String = "profile",
  /** The role assigned to the user within the organization, if applicable. */
  @JsonProperty("role")
  val role: SlimRole? = null,
  /** The roles assigned to the user within the organization, if applicable. */
  @JsonProperty("roles")
  val roles: List<SlimRole>? = null,
  /** The groups the user belongs to, as returned by the identity provider. */
  @JsonProperty("groups")
  val groups: List<String>? = null,
  /** Custom attribute mappings defined for the connection, returned as key-value pairs. */
  @JsonProperty("custom_attributes")
  val customAttributes: Map<String, Any>? = null
)
