// This file is auto-generated by oagen. Do not edit.

package com.workos.models

/** Alias for [RadarStandaloneUpdateRadarListRequest]. */
typealias RadarStandaloneDeleteRadarListEntryRequest = RadarStandaloneUpdateRadarListRequest
