// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** The event payload. */
data class RadarChallengeCreatedData(
  /** The ID of the Radar challenge. */
  @JsonProperty("radar_challenge_id")
  val radarChallengeId: String,

  /** The ID of the user. */
  @JsonProperty("user_id")
  val userId: String,

  /** The email address of the user. */
  @JsonProperty("email")
  val email: String,

  /** The type of the Radar challenge. */
  @JsonProperty("type")
  val type: String = "email"
)
