// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** RedirectUri model. */
data class RedirectUri(
  /** The object type. */
  @JvmField
  @JsonProperty("object")
  val `object`: String,
  /** The ID of the redirect URI. */
  @JvmField
  @JsonProperty("id")
  val id: String,
  /** The redirect URI. */
  @JvmField
  @JsonProperty("uri")
  val uri: String,
  /** Whether this is the default redirect URI. */
  @JvmField
  @JsonProperty("default")
  val default: Boolean,
  /** The timestamp when the redirect URI was created. */
  @JvmField
  @JsonProperty("created_at")
  val createdAt: String,
  /** The timestamp when the redirect URI was last updated. */
  @JvmField
  @JsonProperty("updated_at")
  val updatedAt: String
)
