// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import com.workos.types.ResendUserInviteOptionsLocale

/** ResendUserInviteOptions model. */
data class ResendUserInviteOptions(
  /** The locale to use when rendering the invitation email. See [supported locales](https://workos.com/docs/authkit/hosted-ui/localization). */
  @JvmField
  @JsonProperty("locale")
  val locale: ResendUserInviteOptionsLocale? = null
)
