// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** ResetPasswordResponse model. */
data class ResetPasswordResponse(
  /** The user whose password was reset. */
  @JvmField
  @JsonProperty("user")
  val user: User
)
