// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import com.workos.types.ResourceExportFailedDataResourceType

/** The event payload. */
data class ResourceExportFailedData(
  /** The ID of the resource export. */
  @JsonProperty("id")
  val id: String,

  /** The type of resource being exported. */
  @JsonProperty("resource_type")
  val resourceType: ResourceExportFailedDataResourceType
)
