// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** RevokeSession model. */
data class RevokeSession(
  /** The ID of the session to revoke. This can be extracted from the `sid` claim of the access token. */
  @JvmField
  @JsonProperty("session_id")
  val sessionId: String,
  /** The URL to redirect the user to after session revocation. */
  @JvmField
  @JsonProperty("return_to")
  val returnTo: String? = null
)
