// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** SendRadarSmsChallenge model. */
data class SendRadarSmsChallenge(
  /** The ID of the user to send the SMS challenge to. */
  @JsonProperty("user_id")
  val userId: String,

  /** The pending authentication token from a previous authentication attempt that triggered the Radar challenge. */
  @JsonProperty("pending_authentication_token")
  val pendingAuthenticationToken: String,

  /** The phone number to send the SMS verification code to. */
  @JsonProperty("phone_number")
  val phoneNumber: String,

  /** The IP address of the user's request. */
  @JsonProperty("ip_address")
  val ipAddress: String? = null,

  /** The user agent string from the user's request. */
  @JsonProperty("user_agent")
  val userAgent: String? = null
)
