// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import com.workos.common.http.WorkOSEvent
import java.time.OffsetDateTime

/** SessionRevoked model. */
data class SessionRevoked(
  /** Unique identifier for the event. */
  @JsonProperty("id")
  override val id: String,
  /** The event payload. */
  @JsonProperty("data")
  val data: SessionRevokedData,
  /** An ISO 8601 timestamp. */
  @JsonProperty("created_at")
  override val createdAt: OffsetDateTime,
  /** Always `"session.revoked"`. */
  @JsonProperty("event")
  override val event: String = "session.revoked",
  @JsonProperty("context")
  val context: EventContext? = null,
  /** Distinguishes the Event object. */
  @JsonProperty("object")
  val objectType: String = "event"
) : WorkOSEvent
