// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import com.workos.types.UpdateCustomProviderDefinitionAuthenticateVia

/** UpdateCustomProviderDefinition model. */
data class UpdateCustomProviderDefinition(
  /** A descriptive name for the custom provider. */
  @JsonProperty("name")
  val name: String? = null,

  /** The provider's OAuth authorization endpoint. */
  @JsonProperty("authorization_url")
  val authorizationUrl: String? = null,

  /** The provider's OAuth token endpoint. */
  @JsonProperty("token_url")
  val tokenUrl: String? = null,

  /** The endpoint used to refresh tokens, if different from the token endpoint. */
  @JsonProperty("refresh_token_url")
  val refreshTokenUrl: String? = null,

  /** Whether PKCE is used during the authorization code flow. */
  @JsonProperty("pkce_enabled")
  val pkceEnabled: Boolean? = null,

  /** The separator used to join requested scopes. */
  @JsonProperty("request_scope_separator")
  val requestScopeSeparator: String? = null,

  /** Whether at least one scope must be selected when connecting an account. */
  @JsonProperty("scopes_required")
  val scopesRequired: Boolean? = null,

  /** Whether a client secret is required for this provider. */
  @JsonProperty("client_secret_required")
  val clientSecretRequired: Boolean? = null,

  /** Additional static query parameters appended to the authorization request. */
  @JsonProperty("additional_authorization_parameters")
  val additionalAuthorizationParameters: Map<String, String>? = null,

  /** The Content-Type used when exchanging the token request. */
  @JsonProperty("token_body_content_type")
  val tokenBodyContentType: String? = null,

  /** How client credentials are sent when exchanging authorization codes and refreshing tokens. */
  @JsonProperty("authenticate_via")
  val authenticateVia: UpdateCustomProviderDefinitionAuthenticateVia? = null
)
