// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** UpdateObjectRequest model. */
data class UpdateObjectRequest(
  /** New plaintext value. */
  @JsonProperty("value")
  val value: String,

  /** ID of the expected current version for optimistic locking. */
  @JsonProperty("version_check")
  val versionCheck: String? = null
)
