// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import com.workos.common.http.WorkOSEvent
import java.time.OffsetDateTime

/** UserUpdated model. */
data class UserUpdated(
  /** Unique identifier for the event. */
  @JsonProperty("id")
  override val id: String,
  /** The event payload. */
  @JvmField
  @JsonProperty("data")
  val data: User,
  /** An ISO 8601 timestamp. */
  @JsonProperty("created_at")
  override val createdAt: OffsetDateTime,
  /** Always `"user.updated"`. */
  @JsonProperty("event")
  override val event: String = "user.updated",
  @JvmField
  @JsonProperty("context")
  val context: EventContext? = null,
  /** Distinguishes the Event object. */
  @JvmField
  @JsonProperty("object")
  val `object`: String = "event"
) : WorkOSEvent
