// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** Information about the impersonator if this session was created via impersonation. */
data class UserSessionsImpersonator(
  /** The email address of the WorkOS Dashboard user who is impersonating the user. */
  @JsonProperty("email")
  val email: String,
  /** The justification the impersonator gave for impersonating the user. */
  @JsonProperty("reason")
  val reason: String?
)
