// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** ValidateApiKey model. */
data class ValidateApiKey(
  /** The value for an API key. */
  @JvmField
  @JsonProperty("value")
  val value: String
)
