// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import java.time.OffsetDateTime

/** VaultMetadataRead model. */
data class VaultMetadataRead(
  /** Unique identifier for the event. */
  @JvmField
  @JsonProperty("id")
  val id: String,
  /** The event payload. */
  @JvmField
  @JsonProperty("data")
  val data: VaultMetadataReadData,
  /** An ISO 8601 timestamp. */
  @JvmField
  @JsonProperty("created_at")
  val createdAt: OffsetDateTime,
  /** Always `"vault.metadata.read"`. */
  @JvmField
  @JsonProperty("event")
  val event: String = "vault.metadata.read",
  @JvmField
  @JsonProperty("context")
  val context: EventContext? = null,
  /** Distinguishes the Event object. */
  @JvmField
  @JsonProperty("object")
  val `object`: String = "event"
)
