// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty

/** VerifyEmailResponse model. */
data class VerifyEmailResponse(
  /** The user whose email was verified. */
  @JsonProperty("user")
  val user: User
)
