// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonProperty
import com.workos.types.WidgetSessionTokenScopes

/** WidgetSessionToken model. */
data class WidgetSessionToken(
  /** The ID of the organization to scope the widget session to. */
  @JsonProperty("organization_id")
  val organizationId: String,
  /** The ID of the user to issue the widget session token for. */
  @JsonProperty("user_id")
  val userId: String? = null,
  /** The scopes to grant the widget session. */
  @JsonProperty("scopes")
  val scopes: List<WidgetSessionTokenScopes>? = null
)
