// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo
import java.time.OffsetDateTime

/**
 * Sealed interface for all webhook/event envelope models.
 *
 * Jackson deserializes incoming event JSON to the correct concrete type
 * based on the `event` discriminator field. Unknown event types fall back
 * to [EventSchema] with untyped `data: Map<String, Any>`.
 *
 * ```kotlin
 * val event: WorkOSEvent = objectMapper.readValue(json, WorkOSEvent::class.java)
 * when (event) {
 *   is UserCreated -> println("User created: ${event.data.id}")
 *   is EventSchema -> println("Unknown event: ${event.event}")
 * }
 * ```
 */
@JsonTypeInfo(
  use = JsonTypeInfo.Id.NAME,
  include = JsonTypeInfo.As.EXISTING_PROPERTY,
  property = "event",
  visible = true,
  defaultImpl = EventSchema::class
)
@JsonSubTypes(
  JsonSubTypes.Type(value = ActionAuthenticationDenied::class, name = "action.authentication.denied"),
  JsonSubTypes.Type(value = ActionUserRegistrationDenied::class, name = "action.user_registration.denied"),
  JsonSubTypes.Type(value = ApiKeyCreated::class, name = "api_key.created"),
  JsonSubTypes.Type(value = ApiKeyRevoked::class, name = "api_key.revoked"),
  JsonSubTypes.Type(value = AuthenticationEmailVerificationFailed::class, name = "authentication.email_verification_failed"),
  JsonSubTypes.Type(value = AuthenticationEmailVerificationSucceeded::class, name = "authentication.email_verification_succeeded"),
  JsonSubTypes.Type(value = AuthenticationMagicAuthFailed::class, name = "authentication.magic_auth_failed"),
  JsonSubTypes.Type(value = AuthenticationMagicAuthSucceeded::class, name = "authentication.magic_auth_succeeded"),
  JsonSubTypes.Type(value = AuthenticationMfaFailed::class, name = "authentication.mfa_failed"),
  JsonSubTypes.Type(value = AuthenticationMfaSucceeded::class, name = "authentication.mfa_succeeded"),
  JsonSubTypes.Type(value = AuthenticationOAuthFailed::class, name = "authentication.oauth_failed"),
  JsonSubTypes.Type(value = AuthenticationOAuthSucceeded::class, name = "authentication.oauth_succeeded"),
  JsonSubTypes.Type(value = AuthenticationPasskeyFailed::class, name = "authentication.passkey_failed"),
  JsonSubTypes.Type(value = AuthenticationPasskeySucceeded::class, name = "authentication.passkey_succeeded"),
  JsonSubTypes.Type(value = AuthenticationPasswordFailed::class, name = "authentication.password_failed"),
  JsonSubTypes.Type(value = AuthenticationPasswordSucceeded::class, name = "authentication.password_succeeded"),
  JsonSubTypes.Type(value = AuthenticationRadarRiskDetected::class, name = "authentication.radar_risk_detected"),
  JsonSubTypes.Type(value = AuthenticationSSOFailed::class, name = "authentication.sso_failed"),
  JsonSubTypes.Type(value = AuthenticationSSOStarted::class, name = "authentication.sso_started"),
  JsonSubTypes.Type(value = AuthenticationSSOSucceeded::class, name = "authentication.sso_succeeded"),
  JsonSubTypes.Type(value = AuthenticationSSOTimedOut::class, name = "authentication.sso_timed_out"),
  JsonSubTypes.Type(value = ConnectionActivated::class, name = "connection.activated"),
  JsonSubTypes.Type(value = ConnectionDeactivated::class, name = "connection.deactivated"),
  JsonSubTypes.Type(value = ConnectionDeleted::class, name = "connection.deleted"),
  JsonSubTypes.Type(value = ConnectionSAMLCertificateRenewalRequired::class, name = "connection.saml_certificate_renewal_required"),
  JsonSubTypes.Type(value = ConnectionSAMLCertificateRenewed::class, name = "connection.saml_certificate_renewed"),
  JsonSubTypes.Type(value = DsyncActivated::class, name = "dsync.activated"),
  JsonSubTypes.Type(value = DsyncDeactivated::class, name = "dsync.deactivated"),
  JsonSubTypes.Type(value = DsyncDeleted::class, name = "dsync.deleted"),
  JsonSubTypes.Type(value = DsyncGroupCreated::class, name = "dsync.group.created"),
  JsonSubTypes.Type(value = DsyncGroupDeleted::class, name = "dsync.group.deleted"),
  JsonSubTypes.Type(value = DsyncGroupUpdated::class, name = "dsync.group.updated"),
  JsonSubTypes.Type(value = DsyncGroupUserAdded::class, name = "dsync.group.user_added"),
  JsonSubTypes.Type(value = DsyncGroupUserRemoved::class, name = "dsync.group.user_removed"),
  JsonSubTypes.Type(value = DsyncUserCreated::class, name = "dsync.user.created"),
  JsonSubTypes.Type(value = DsyncUserDeleted::class, name = "dsync.user.deleted"),
  JsonSubTypes.Type(value = DsyncUserUpdated::class, name = "dsync.user.updated"),
  JsonSubTypes.Type(value = EmailVerificationCreated::class, name = "email_verification.created"),
  JsonSubTypes.Type(value = FlagCreated::class, name = "flag.created"),
  JsonSubTypes.Type(value = FlagDeleted::class, name = "flag.deleted"),
  JsonSubTypes.Type(value = FlagRuleUpdated::class, name = "flag.rule_updated"),
  JsonSubTypes.Type(value = FlagUpdated::class, name = "flag.updated"),
  JsonSubTypes.Type(value = GroupCreated::class, name = "group.created"),
  JsonSubTypes.Type(value = GroupDeleted::class, name = "group.deleted"),
  JsonSubTypes.Type(value = GroupMemberAdded::class, name = "group.member_added"),
  JsonSubTypes.Type(value = GroupMemberRemoved::class, name = "group.member_removed"),
  JsonSubTypes.Type(value = GroupUpdated::class, name = "group.updated"),
  JsonSubTypes.Type(value = InvitationAccepted::class, name = "invitation.accepted"),
  JsonSubTypes.Type(value = InvitationCreated::class, name = "invitation.created"),
  JsonSubTypes.Type(value = InvitationResent::class, name = "invitation.resent"),
  JsonSubTypes.Type(value = InvitationRevoked::class, name = "invitation.revoked"),
  JsonSubTypes.Type(value = MagicAuthCreated::class, name = "magic_auth.created"),
  JsonSubTypes.Type(value = OrganizationDomainCreated::class, name = "organization_domain.created"),
  JsonSubTypes.Type(value = OrganizationDomainDeleted::class, name = "organization_domain.deleted"),
  JsonSubTypes.Type(value = OrganizationDomainUpdated::class, name = "organization_domain.updated"),
  JsonSubTypes.Type(value = OrganizationDomainVerificationFailed::class, name = "organization_domain.verification_failed"),
  JsonSubTypes.Type(value = OrganizationDomainVerified::class, name = "organization_domain.verified"),
  JsonSubTypes.Type(value = OrganizationMembershipCreated::class, name = "organization_membership.created"),
  JsonSubTypes.Type(value = OrganizationMembershipDeleted::class, name = "organization_membership.deleted"),
  JsonSubTypes.Type(value = OrganizationMembershipUpdated::class, name = "organization_membership.updated"),
  JsonSubTypes.Type(value = OrganizationRoleCreated::class, name = "organization_role.created"),
  JsonSubTypes.Type(value = OrganizationRoleDeleted::class, name = "organization_role.deleted"),
  JsonSubTypes.Type(value = OrganizationRoleUpdated::class, name = "organization_role.updated"),
  JsonSubTypes.Type(value = OrganizationCreated::class, name = "organization.created"),
  JsonSubTypes.Type(value = OrganizationDeleted::class, name = "organization.deleted"),
  JsonSubTypes.Type(value = OrganizationUpdated::class, name = "organization.updated"),
  JsonSubTypes.Type(value = PasswordResetCreated::class, name = "password_reset.created"),
  JsonSubTypes.Type(value = PasswordResetSucceeded::class, name = "password_reset.succeeded"),
  JsonSubTypes.Type(value = PermissionCreated::class, name = "permission.created"),
  JsonSubTypes.Type(value = PermissionDeleted::class, name = "permission.deleted"),
  JsonSubTypes.Type(value = PermissionUpdated::class, name = "permission.updated"),
  JsonSubTypes.Type(value = RoleCreated::class, name = "role.created"),
  JsonSubTypes.Type(value = RoleDeleted::class, name = "role.deleted"),
  JsonSubTypes.Type(value = RoleUpdated::class, name = "role.updated"),
  JsonSubTypes.Type(value = SessionCreated::class, name = "session.created"),
  JsonSubTypes.Type(value = SessionRevoked::class, name = "session.revoked"),
  JsonSubTypes.Type(value = UserCreated::class, name = "user.created"),
  JsonSubTypes.Type(value = UserDeleted::class, name = "user.deleted"),
  JsonSubTypes.Type(value = UserUpdated::class, name = "user.updated"),
  JsonSubTypes.Type(value = VaultByokKeyVerificationCompleted::class, name = "vault.byok_key.verification_completed"),
  JsonSubTypes.Type(value = VaultDataCreated::class, name = "vault.data.created"),
  JsonSubTypes.Type(value = VaultDataDeleted::class, name = "vault.data.deleted"),
  JsonSubTypes.Type(value = VaultDataRead::class, name = "vault.data.read"),
  JsonSubTypes.Type(value = VaultDataUpdated::class, name = "vault.data.updated"),
  JsonSubTypes.Type(value = VaultDekDecrypted::class, name = "vault.dek.decrypted"),
  JsonSubTypes.Type(value = VaultDekRead::class, name = "vault.dek.read"),
  JsonSubTypes.Type(value = VaultKekCreated::class, name = "vault.kek.created"),
  JsonSubTypes.Type(value = VaultMetadataRead::class, name = "vault.metadata.read"),
  JsonSubTypes.Type(value = VaultNamesListed::class, name = "vault.names.listed"),
  JsonSubTypes.Type(value = WaitlistUserApproved::class, name = "waitlist_user.approved"),
  JsonSubTypes.Type(value = WaitlistUserCreated::class, name = "waitlist_user.created"),
  JsonSubTypes.Type(value = WaitlistUserDenied::class, name = "waitlist_user.denied")
)
sealed interface WorkOSEvent {
  /** Unique identifier for this event. */
  val id: String

  /** The event type identifier. */
  val event: String

  /** Timestamp when the event was created. */
  val createdAt: OffsetDateTime
}
