// This file is auto-generated by oagen. Do not edit.

package com.workos.featureflags

import com.fasterxml.jackson.core.type.TypeReference
import com.workos.WorkOS
import com.workos.common.http.Page
import com.workos.common.http.RequestConfig
import com.workos.common.http.RequestOptions
import com.workos.common.http.encodePathSegment
import com.workos.models.FeatureFlag
import com.workos.models.Flag
import com.workos.types.PaginationOrder
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * API accessor for FeatureFlags.
 *
 * Every operation on this class is available in two flavors: a blocking variant (`<methodName>`) and a coroutine-aware variant (`<methodName>Suspend`). The `Suspend` variants delegate to the blocking ones under `withContext(Dispatchers.IO)`, so they are safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
 */
class FeatureFlags(
  internal val workos: WorkOS
) {
  /**
   * List feature flags
   *
   * Get a list of all of your existing feature flags matching the criteria specified.
   *
   * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
   * @param after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
   * @param limit Upper limit on the number of objects to return, between `1` and `100`.
   * @param order Order the results by the creation time.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return a [com.workos.common.http.Page] of results
   */
  @JvmOverloads
  fun list(
    before: String? = null,
    after: String? = null,
    limit: Int? = null,
    order: PaginationOrder? = null,
    requestOptions: RequestOptions? = null
  ): Page<Flag> {
    val itemType = object : TypeReference<Flag>() {}
    return workos.baseClient.requestPage(
      method = "GET",
      path = "/feature-flags",
      itemType = itemType,
      requestOptions = requestOptions,
      before = before,
      after = after
    ) {
      limit?.let { add("limit" to it.toString()) }
      order?.let { add("order" to it.value) }
    }
  }

  /**
   * Coroutine-aware variant of [list]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [list] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("listSuspend")
  suspend fun listSuspend(
    before: String? = null,
    after: String? = null,
    limit: Int? = null,
    order: PaginationOrder? = null,
    requestOptions: RequestOptions? = null
  ): Page<Flag> =
    withContext(Dispatchers.IO) {
      list(before, after, limit, order, requestOptions)
    }

  /**
   * Get a feature flag
   *
   * Get the details of an existing feature flag by its slug.
   *
   * @param slug A unique key to reference the Feature Flag.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the Flag
   */
  @JvmOverloads
  fun get(
    slug: String,
    requestOptions: RequestOptions? = null
  ): Flag {
    val config =
      RequestConfig(
        method = "GET",
        path = "/feature-flags/${encodePathSegment(slug)}",
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, Flag::class.java)
  }

  /**
   * Coroutine-aware variant of [get]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [get] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("getSuspend")
  suspend fun getSuspend(
    slug: String,
    requestOptions: RequestOptions? = null
  ): Flag =
    withContext(Dispatchers.IO) {
      get(slug, requestOptions)
    }

  /**
   * Disable a feature flag
   *
   * Disables a feature flag in the current environment.
   *
   * @param slug A unique key to reference the Feature Flag.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the FeatureFlag
   */
  @JvmOverloads
  fun disable(
    slug: String,
    requestOptions: RequestOptions? = null
  ): FeatureFlag {
    val body = linkedMapOf<String, Any?>()
    val config =
      RequestConfig(
        method = "PUT",
        path = "/feature-flags/${encodePathSegment(slug)}/disable",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, FeatureFlag::class.java)
  }

  /**
   * Coroutine-aware variant of [disable]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [disable] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("disableSuspend")
  suspend fun disableSuspend(
    slug: String,
    requestOptions: RequestOptions? = null
  ): FeatureFlag =
    withContext(Dispatchers.IO) {
      disable(slug, requestOptions)
    }

  /**
   * Enable a feature flag
   *
   * Enables a feature flag in the current environment.
   *
   * @param slug A unique key to reference the Feature Flag.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the FeatureFlag
   */
  @JvmOverloads
  fun enable(
    slug: String,
    requestOptions: RequestOptions? = null
  ): FeatureFlag {
    val body = linkedMapOf<String, Any?>()
    val config =
      RequestConfig(
        method = "PUT",
        path = "/feature-flags/${encodePathSegment(slug)}/enable",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, FeatureFlag::class.java)
  }

  /**
   * Coroutine-aware variant of [enable]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [enable] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("enableSuspend")
  suspend fun enableSuspend(
    slug: String,
    requestOptions: RequestOptions? = null
  ): FeatureFlag =
    withContext(Dispatchers.IO) {
      enable(slug, requestOptions)
    }

  /**
   * Add a feature flag target
   *
   * Enables a feature flag for a specific target in the current environment. Currently, supported targets include users and organizations.
   *
   * @param slug The unique slug identifier of the feature flag.
   * @param resourceId The resource ID in format "user_<id>" or "org_<id>".
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   */
  @JvmOverloads
  fun addFlagTarget(
    slug: String,
    resourceId: String,
    requestOptions: RequestOptions? = null
  ) {
    val body = linkedMapOf<String, Any?>()
    val config =
      RequestConfig(
        method = "POST",
        path = "/feature-flags/${encodePathSegment(slug)}/targets/${encodePathSegment(resourceId)}",
        body = body,
        requestOptions = requestOptions
      )
    workos.baseClient.requestVoid(config)
  }

  /**
   * Coroutine-aware variant of [addFlagTarget]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [addFlagTarget] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("addFlagTargetSuspend")
  suspend fun addFlagTargetSuspend(
    slug: String,
    resourceId: String,
    requestOptions: RequestOptions? = null
  ) = withContext(Dispatchers.IO) {
    addFlagTarget(slug, resourceId, requestOptions)
  }

  /**
   * Remove a feature flag target
   *
   * Removes a target from the feature flag's target list in the current environment. Currently, supported targets include users and organizations.
   *
   * @param slug The unique slug identifier of the feature flag.
   * @param resourceId The resource ID in format "user_<id>" or "org_<id>".
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   */
  @JvmOverloads
  fun removeFlagTarget(
    slug: String,
    resourceId: String,
    requestOptions: RequestOptions? = null
  ) {
    val config =
      RequestConfig(
        method = "DELETE",
        path = "/feature-flags/${encodePathSegment(slug)}/targets/${encodePathSegment(resourceId)}",
        requestOptions = requestOptions
      )
    workos.baseClient.requestVoid(config)
  }

  /**
   * Coroutine-aware variant of [removeFlagTarget]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [removeFlagTarget] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("removeFlagTargetSuspend")
  suspend fun removeFlagTargetSuspend(
    slug: String,
    resourceId: String,
    requestOptions: RequestOptions? = null
  ) = withContext(Dispatchers.IO) {
    removeFlagTarget(slug, resourceId, requestOptions)
  }

  /**
   * List enabled feature flags for an organization
   *
   * Get a list of all enabled feature flags for an organization.
   *
   * @param organizationId Unique identifier of the Organization.
   * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
   * @param after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
   * @param limit Upper limit on the number of objects to return, between `1` and `100`.
   * @param order Order the results by the creation time.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return a [com.workos.common.http.Page] of results
   */
  @JvmOverloads
  fun listOrganizationFeatureFlags(
    organizationId: String,
    before: String? = null,
    after: String? = null,
    limit: Int? = null,
    order: PaginationOrder? = null,
    requestOptions: RequestOptions? = null
  ): Page<Flag> {
    val itemType = object : TypeReference<Flag>() {}
    return workos.baseClient.requestPage(
      method = "GET",
      path = "/organizations/${encodePathSegment(organizationId)}/feature-flags",
      itemType = itemType,
      requestOptions = requestOptions,
      before = before,
      after = after
    ) {
      limit?.let { add("limit" to it.toString()) }
      order?.let { add("order" to it.value) }
    }
  }

  /**
   * Coroutine-aware variant of [listOrganizationFeatureFlags]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [listOrganizationFeatureFlags] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("listOrganizationFeatureFlagsSuspend")
  suspend fun listOrganizationFeatureFlagsSuspend(
    organizationId: String,
    before: String? = null,
    after: String? = null,
    limit: Int? = null,
    order: PaginationOrder? = null,
    requestOptions: RequestOptions? = null
  ): Page<Flag> =
    withContext(Dispatchers.IO) {
      listOrganizationFeatureFlags(organizationId, before, after, limit, order, requestOptions)
    }

  /**
   * List enabled feature flags for a user
   *
   * Get a list of all enabled feature flags for the provided user. This includes feature flags enabled specifically for the user as well as any organizations that the user is a member of.
   *
   * @param userId The ID of the user.
   * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
   * @param after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
   * @param limit Upper limit on the number of objects to return, between `1` and `100`.
   * @param order Order the results by the creation time.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return a [com.workos.common.http.Page] of results
   */
  @JvmOverloads
  fun listUserFeatureFlags(
    userId: String,
    before: String? = null,
    after: String? = null,
    limit: Int? = null,
    order: PaginationOrder? = null,
    requestOptions: RequestOptions? = null
  ): Page<Flag> {
    val itemType = object : TypeReference<Flag>() {}
    return workos.baseClient.requestPage(
      method = "GET",
      path = "/user_management/users/${encodePathSegment(userId)}/feature-flags",
      itemType = itemType,
      requestOptions = requestOptions,
      before = before,
      after = after
    ) {
      limit?.let { add("limit" to it.toString()) }
      order?.let { add("order" to it.value) }
    }
  }

  /**
   * Coroutine-aware variant of [listUserFeatureFlags]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [listUserFeatureFlags] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("listUserFeatureFlagsSuspend")
  suspend fun listUserFeatureFlagsSuspend(
    userId: String,
    before: String? = null,
    after: String? = null,
    limit: Int? = null,
    order: PaginationOrder? = null,
    requestOptions: RequestOptions? = null
  ): Page<Flag> =
    withContext(Dispatchers.IO) {
      listUserFeatureFlags(userId, before, after, limit, order, requestOptions)
    }
}
