// This file is auto-generated by oagen. Do not edit.

package com.workos.pipes

import com.workos.WorkOS
import com.workos.common.http.RequestConfig
import com.workos.common.http.RequestOptions
import com.workos.common.http.addIfNotNull
import com.workos.common.http.bodyOf
import com.workos.common.http.encodePathSegment
import com.workos.models.ConnectedAccount
import com.workos.models.DataIntegrationAccessTokenResponse
import com.workos.models.DataIntegrationAuthorizeUrlResponse
import com.workos.models.DataIntegrationCredentialsResponse
import com.workos.models.DataIntegrationsListResponse
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * API accessor for Pipes.
 *
 * Every operation on this class is available in two flavors: a blocking variant (`<methodName>`) and a coroutine-aware variant (`<methodName>Suspend`). The `Suspend` variants delegate to the blocking ones under `withContext(Dispatchers.IO)`, so they are safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
 */
class Pipes(
  internal val workos: WorkOS
) {
  /**
   * Upsert an API key for a connected account
   *
   * Creates or updates an API-key-based installation for the specified integration and user. If an installation already exists, the stored API key is rotated to the new value.
   *
   * @param slug The identifier of the integration.
   * @param userId A [User](https://workos.com/docs/reference/authkit/user) identifier.
   * @param secret The API key secret to store for this integration.
   * @param organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the ConnectedAccount
   */
  @JvmOverloads
  fun updateDataIntegrationApiKey(
    slug: String,
    userId: String,
    secret: String,
    organizationId: String? = null,
    requestOptions: RequestOptions? = null
  ): ConnectedAccount {
    val body =
      bodyOf(
        "user_id" to userId,
        "secret" to secret,
        "organization_id" to organizationId
      )
    val config =
      RequestConfig(
        method = "PUT",
        path = "/data-integrations/${encodePathSegment(slug)}/api-key",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, ConnectedAccount::class.java)
  }

  /**
   * Coroutine-aware variant of [updateDataIntegrationApiKey]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [updateDataIntegrationApiKey] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("updateDataIntegrationApiKeySuspend")
  suspend fun updateDataIntegrationApiKeySuspend(
    slug: String,
    userId: String,
    secret: String,
    organizationId: String? = null,
    requestOptions: RequestOptions? = null
  ): ConnectedAccount =
    withContext(Dispatchers.IO) {
      updateDataIntegrationApiKey(slug, userId, secret, organizationId, requestOptions)
    }

  /**
   * Get authorization URL
   *
   * Generates an OAuth authorization URL to initiate the connection flow for a user. Redirect the user to the returned URL to begin the OAuth flow with the third-party provider.
   *
   * @param slug The slug identifier of the provider (e.g., `github`, `slack`, `notion`).
   * @param userId The ID of the user to authorize.
   * @param organizationId An organization ID to scope the authorization to a specific organization.
   * @param returnTo The URL to redirect the user to after authorization.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the DataIntegrationAuthorizeUrlResponse
   */
  @JvmOverloads
  fun authorizeDataIntegration(
    slug: String,
    userId: String,
    organizationId: String? = null,
    returnTo: String? = null,
    requestOptions: RequestOptions? = null
  ): DataIntegrationAuthorizeUrlResponse {
    val body =
      bodyOf(
        "user_id" to userId,
        "organization_id" to organizationId,
        "return_to" to returnTo
      )
    val config =
      RequestConfig(
        method = "POST",
        path = "/data-integrations/${encodePathSegment(slug)}/authorize",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, DataIntegrationAuthorizeUrlResponse::class.java)
  }

  /**
   * Coroutine-aware variant of [authorizeDataIntegration]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [authorizeDataIntegration] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("authorizeDataIntegrationSuspend")
  suspend fun authorizeDataIntegrationSuspend(
    slug: String,
    userId: String,
    organizationId: String? = null,
    returnTo: String? = null,
    requestOptions: RequestOptions? = null
  ): DataIntegrationAuthorizeUrlResponse =
    withContext(Dispatchers.IO) {
      authorizeDataIntegration(slug, userId, organizationId, returnTo, requestOptions)
    }

  /**
   * Vend credentials for a connected account
   *
   * Returns credentials for a user's connected account. Branches on the installation's `auth_method`: OAuth installations return an access token (refreshed if needed); API-key installations return the stored secret.
   *
   * @param slug The identifier of the integration.
   * @param userId A [User](https://workos.com/docs/reference/authkit/user) identifier.
   * @param organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the DataIntegrationCredentialsResponse
   */
  @JvmOverloads
  fun createDataIntegrationCredential(
    slug: String,
    userId: String,
    organizationId: String? = null,
    requestOptions: RequestOptions? = null
  ): DataIntegrationCredentialsResponse {
    val body =
      bodyOf(
        "user_id" to userId,
        "organization_id" to organizationId
      )
    val config =
      RequestConfig(
        method = "POST",
        path = "/data-integrations/${encodePathSegment(slug)}/credentials",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, DataIntegrationCredentialsResponse::class.java)
  }

  /**
   * Coroutine-aware variant of [createDataIntegrationCredential]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [createDataIntegrationCredential] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("createDataIntegrationCredentialSuspend")
  suspend fun createDataIntegrationCredentialSuspend(
    slug: String,
    userId: String,
    organizationId: String? = null,
    requestOptions: RequestOptions? = null
  ): DataIntegrationCredentialsResponse =
    withContext(Dispatchers.IO) {
      createDataIntegrationCredential(slug, userId, organizationId, requestOptions)
    }

  /**
   * Get an access token for a connected account
   *
   * Fetches a valid OAuth access token for a user's connected account. WorkOS automatically handles token refresh, ensuring you always receive a valid, non-expired token.
   *
   * @param provider The identifier of the integration.
   * @param userId A [User](https://workos.com/docs/reference/authkit/user) identifier.
   * @param organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the DataIntegrationAccessTokenResponse
   */
  @JvmOverloads
  fun getAccessToken(
    provider: String,
    userId: String,
    organizationId: String? = null,
    requestOptions: RequestOptions? = null
  ): DataIntegrationAccessTokenResponse {
    val body =
      bodyOf(
        "user_id" to userId,
        "organization_id" to organizationId
      )
    val config =
      RequestConfig(
        method = "POST",
        path = "/data-integrations/${encodePathSegment(provider)}/token",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, DataIntegrationAccessTokenResponse::class.java)
  }

  /**
   * Coroutine-aware variant of [getAccessToken]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [getAccessToken] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("getAccessTokenSuspend")
  suspend fun getAccessTokenSuspend(
    provider: String,
    userId: String,
    organizationId: String? = null,
    requestOptions: RequestOptions? = null
  ): DataIntegrationAccessTokenResponse =
    withContext(Dispatchers.IO) {
      getAccessToken(provider, userId, organizationId, requestOptions)
    }

  /**
   * Get a connected account
   *
   * Retrieves a user's [connected account](https://workos.com/docs/reference/pipes/connected-account) for a specific provider.
   *
   * @param userId A [User](https://workos.com/docs/reference/authkit/user) identifier.
   * @param slug The slug identifier of the provider (e.g., `github`, `slack`, `notion`).
   * @param organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter if the connection is scoped to an organization.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the ConnectedAccount
   */
  @JvmOverloads
  fun getUserConnectedAccount(
    userId: String,
    slug: String,
    organizationId: String? = null,
    requestOptions: RequestOptions? = null
  ): ConnectedAccount {
    val params = mutableListOf<Pair<String, String>>()
    params.addIfNotNull("organization_id", organizationId)
    val config =
      RequestConfig(
        method = "GET",
        path = "/user_management/users/${encodePathSegment(userId)}/connected_accounts/${encodePathSegment(slug)}",
        queryParams = params,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, ConnectedAccount::class.java)
  }

  /**
   * Coroutine-aware variant of [getUserConnectedAccount]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [getUserConnectedAccount] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("getUserConnectedAccountSuspend")
  suspend fun getUserConnectedAccountSuspend(
    userId: String,
    slug: String,
    organizationId: String? = null,
    requestOptions: RequestOptions? = null
  ): ConnectedAccount =
    withContext(Dispatchers.IO) {
      getUserConnectedAccount(userId, slug, organizationId, requestOptions)
    }

  /**
   * Delete a connected account
   *
   * Disconnects WorkOS's account for the user, including removing any stored access and refresh tokens. The user will need to reauthorize if they want to reconnect. This does not revoke access on the provider side.
   *
   * @param userId A [User](https://workos.com/docs/reference/authkit/user) identifier.
   * @param slug The slug identifier of the provider (e.g., `github`, `slack`, `notion`).
   * @param organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter if the connection is scoped to an organization.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   */
  @JvmOverloads
  fun deleteUserConnectedAccount(
    userId: String,
    slug: String,
    organizationId: String? = null,
    requestOptions: RequestOptions? = null
  ) {
    val params = mutableListOf<Pair<String, String>>()
    params.addIfNotNull("organization_id", organizationId)
    val config =
      RequestConfig(
        method = "DELETE",
        path = "/user_management/users/${encodePathSegment(userId)}/connected_accounts/${encodePathSegment(slug)}",
        queryParams = params,
        requestOptions = requestOptions
      )
    workos.baseClient.requestVoid(config)
  }

  /**
   * Coroutine-aware variant of [deleteUserConnectedAccount]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [deleteUserConnectedAccount] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("deleteUserConnectedAccountSuspend")
  suspend fun deleteUserConnectedAccountSuspend(
    userId: String,
    slug: String,
    organizationId: String? = null,
    requestOptions: RequestOptions? = null
  ) = withContext(Dispatchers.IO) {
    deleteUserConnectedAccount(userId, slug, organizationId, requestOptions)
  }

  /**
   * List providers for a user
   *
   * Retrieves a list of available providers and the user's connection status for each. Returns all providers configured for your environment, along with the user's [connected account](https://workos.com/docs/reference/pipes/connected-account) information where applicable.
   *
   * @param userId A [User](https://workos.com/docs/reference/authkit/user) identifier to list providers and connected accounts for.
   * @param organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to filter connections for a specific organization.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the DataIntegrationsListResponse
   */
  @JvmOverloads
  fun listUserDataProviders(
    userId: String,
    organizationId: String? = null,
    requestOptions: RequestOptions? = null
  ): DataIntegrationsListResponse {
    val params = mutableListOf<Pair<String, String>>()
    params.addIfNotNull("organization_id", organizationId)
    val config =
      RequestConfig(
        method = "GET",
        path = "/user_management/users/${encodePathSegment(userId)}/data_providers",
        queryParams = params,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, DataIntegrationsListResponse::class.java)
  }

  /**
   * Coroutine-aware variant of [listUserDataProviders]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [listUserDataProviders] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("listUserDataProvidersSuspend")
  suspend fun listUserDataProvidersSuspend(
    userId: String,
    organizationId: String? = null,
    requestOptions: RequestOptions? = null
  ): DataIntegrationsListResponse =
    withContext(Dispatchers.IO) {
      listUserDataProviders(userId, organizationId, requestOptions)
    }
}
