// This file is auto-generated by oagen. Do not edit.

package com.workos.models

import com.workos.common.json.ObjectMapperFactory
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class GeneratedModelRoundTripTest {
  @Test
  fun `ValidateApiKey round-trips through Jackson`() {
    val mapper = ObjectMapperFactory.create()
    val json = "{\"value\": \"sample\"}"
    val parsed = mapper.readValue(json, ValidateApiKey::class.java)
    val reserialized = mapper.writeValueAsString(parsed)
    val tree1 = mapper.readTree(json)
    val tree2 = mapper.readTree(reserialized)
    assertEquals(tree1, tree2)
  }
}
