// This file is auto-generated by oagen. Do not edit.

package com.workos.usermanagement

import com.fasterxml.jackson.core.type.TypeReference
import com.workos.WorkOS
import com.workos.common.http.Page
import com.workos.common.http.RequestConfig
import com.workos.common.http.RequestOptions
import com.workos.common.http.addIfNotNull
import com.workos.common.http.bodyOf
import com.workos.common.http.encodePathSegment
import com.workos.models.AuthenticateResponse
import com.workos.models.AuthorizedConnectApplicationListData
import com.workos.models.CorsOriginResponse
import com.workos.models.DeviceAuthorizationResponse
import com.workos.models.EmailChange
import com.workos.models.EmailChangeConfirmation
import com.workos.models.EmailVerification
import com.workos.models.Invitation
import com.workos.models.JWTTemplateResponse
import com.workos.models.JwksResponse
import com.workos.models.MagicAuth
import com.workos.models.PasswordReset
import com.workos.models.RedirectUri
import com.workos.models.ResetPasswordResponse
import com.workos.models.SendVerificationEmailResponse
import com.workos.models.User
import com.workos.models.UserApiKey
import com.workos.models.UserApiKeyWithValue
import com.workos.models.UserIdentitiesGetItem
import com.workos.models.UserInvite
import com.workos.models.UserSessionsListItem
import com.workos.models.VerifyEmailResponse
import com.workos.types.CreateUserInviteOptionsLocale
import com.workos.types.CreateUserPasswordHashType
import com.workos.types.PaginationOrder
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.time.OffsetDateTime

/**
 * Mutually exclusive password parameter variants.
 *
 * Usage from Kotlin:
 * ```kotlin
 * val target: CreateUserPassword = CreateUserPassword.Plaintext(password = "...")
 * ```
 *
 * Usage from Java:
 * ```java
 * CreateUserPassword target = new CreateUserPassword.Plaintext("...");
 * ```
 *
 * Java callers may also use the per-variant overloads on the surrounding API class to skip variant construction entirely.
 */
sealed class CreateUserPassword {
  /** Variant: plaintext. */
  data class Plaintext(
    /** The password. */
    val password: String
  ) : CreateUserPassword()

  /** Variant: hashed. */
  data class Hashed(
    /** The password hash. */
    val hash: String,
    /** The password hash type. */
    val hashType: CreateUserPasswordHashType
  ) : CreateUserPassword()
}

/**
 * API accessor for UserManagement.
 *
 * Every operation on this class is available in two flavors: a blocking variant (`<methodName>`) and a coroutine-aware variant (`<methodName>Suspend`). The `Suspend` variants delegate to the blocking ones under `withContext(Dispatchers.IO)`, so they are safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
 */
class UserManagement(
  internal val workos: WorkOS
) {
  private fun authenticate(
    grantType: String,
    requestOptions: RequestOptions?,
    vararg entries: Pair<String, Any?>
  ): AuthenticateResponse {
    val body =
      bodyOf(
        *entries,
        "grant_type" to grantType,
        "client_id" to workos.clientId,
        "client_secret" to workos.apiKey
      )
    val config =
      RequestConfig(
        method = "POST",
        path = "/user_management/authenticate",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, AuthenticateResponse::class.java)
  }

  /**
   * Get JWKS
   *
   * Returns the JSON Web Key Set (JWKS) containing the public keys used for verifying access tokens.
   *
   * @param clientId Identifies the application making the request to the WorkOS server. You can obtain your client ID from the [API Keys](https://dashboard.workos.com/api-keys) page in the dashboard.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the JwksResponse
   */
  @JvmOverloads
  fun getJwks(
    clientId: String,
    requestOptions: RequestOptions? = null
  ): JwksResponse {
    val config =
      RequestConfig(
        method = "GET",
        path = "/sso/jwks/${encodePathSegment(clientId)}",
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, JwksResponse::class.java)
  }

  /**
   * Coroutine-aware variant of [getJwks]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [getJwks] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("getJwksSuspend")
  suspend fun getJwksSuspend(
    clientId: String,
    requestOptions: RequestOptions? = null
  ): JwksResponse =
    withContext(Dispatchers.IO) {
      getJwks(clientId, requestOptions)
    }

  /**
   * Authenticate
   *
   * @param email The user's email address.
   * @param password The user's password.
   * @param invitationToken An invitation token to accept during authentication.
   * @param ipAddress The IP address of the user's request.
   * @param deviceId A unique identifier for the device.
   * @param userAgent The user agent string from the user's browser.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   * @return the AuthenticateResponse
   */
  @JvmOverloads
  fun authenticateWithPassword(
    email: String,
    password: String,
    invitationToken: String? = null,
    ipAddress: String? = null,
    deviceId: String? = null,
    userAgent: String? = null,
    requestOptions: RequestOptions? = null
  ): AuthenticateResponse =
    authenticate(
      grantType = "password",
      requestOptions = requestOptions,
      "email" to email,
      "password" to password,
      "invitation_token" to invitationToken,
      "ip_address" to ipAddress,
      "device_id" to deviceId,
      "user_agent" to userAgent
    )

  /**
   * Coroutine-aware variant of [authenticateWithPassword]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [authenticateWithPassword] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("authenticateWithPasswordSuspend")
  suspend fun authenticateWithPasswordSuspend(
    email: String,
    password: String,
    invitationToken: String? = null,
    ipAddress: String? = null,
    deviceId: String? = null,
    userAgent: String? = null,
    requestOptions: RequestOptions? = null
  ): AuthenticateResponse =
    withContext(Dispatchers.IO) {
      authenticateWithPassword(email, password, invitationToken, ipAddress, deviceId, userAgent, requestOptions)
    }

  /**
   * Authenticate
   *
   * @param code The authorization code received from the redirect.
   * @param codeVerifier The PKCE code verifier used to derive the code challenge passed to the authorization URL.
   * @param invitationToken An invitation token to accept during authentication.
   * @param ipAddress The IP address of the user's request.
   * @param deviceId A unique identifier for the device.
   * @param userAgent The user agent string from the user's browser.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   * @return the AuthenticateResponse
   */
  @JvmOverloads
  fun authenticateWithCode(
    code: String,
    codeVerifier: String? = null,
    invitationToken: String? = null,
    ipAddress: String? = null,
    deviceId: String? = null,
    userAgent: String? = null,
    requestOptions: RequestOptions? = null
  ): AuthenticateResponse =
    authenticate(
      grantType = "authorization_code",
      requestOptions = requestOptions,
      "code" to code,
      "code_verifier" to codeVerifier,
      "invitation_token" to invitationToken,
      "ip_address" to ipAddress,
      "device_id" to deviceId,
      "user_agent" to userAgent
    )

  /**
   * Coroutine-aware variant of [authenticateWithCode]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [authenticateWithCode] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("authenticateWithCodeSuspend")
  suspend fun authenticateWithCodeSuspend(
    code: String,
    codeVerifier: String? = null,
    invitationToken: String? = null,
    ipAddress: String? = null,
    deviceId: String? = null,
    userAgent: String? = null,
    requestOptions: RequestOptions? = null
  ): AuthenticateResponse =
    withContext(Dispatchers.IO) {
      authenticateWithCode(code, codeVerifier, invitationToken, ipAddress, deviceId, userAgent, requestOptions)
    }

  /**
   * Authenticate
   *
   * @param refreshToken The refresh token to exchange for new tokens.
   * @param organizationId The ID of the organization to scope the session to.
   * @param ipAddress The IP address of the user's request.
   * @param deviceId A unique identifier for the device.
   * @param userAgent The user agent string from the user's browser.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   * @return the AuthenticateResponse
   */
  @JvmOverloads
  fun authenticateWithRefreshToken(
    refreshToken: String,
    organizationId: String? = null,
    ipAddress: String? = null,
    deviceId: String? = null,
    userAgent: String? = null,
    requestOptions: RequestOptions? = null
  ): AuthenticateResponse =
    authenticate(
      grantType = "refresh_token",
      requestOptions = requestOptions,
      "refresh_token" to refreshToken,
      "organization_id" to organizationId,
      "ip_address" to ipAddress,
      "device_id" to deviceId,
      "user_agent" to userAgent
    )

  /**
   * Coroutine-aware variant of [authenticateWithRefreshToken]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [authenticateWithRefreshToken] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("authenticateWithRefreshTokenSuspend")
  suspend fun authenticateWithRefreshTokenSuspend(
    refreshToken: String,
    organizationId: String? = null,
    ipAddress: String? = null,
    deviceId: String? = null,
    userAgent: String? = null,
    requestOptions: RequestOptions? = null
  ): AuthenticateResponse =
    withContext(Dispatchers.IO) {
      authenticateWithRefreshToken(refreshToken, organizationId, ipAddress, deviceId, userAgent, requestOptions)
    }

  /**
   * Authenticate
   *
   * @param code the code of the request.
   * @param email the email of the request.
   * @param invitationToken the invitation token of the request.
   * @param ipAddress the ip address of the request.
   * @param deviceId the device id of the request.
   * @param userAgent the user agent of the request.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   * @return the AuthenticateResponse
   */
  @JvmOverloads
  fun authenticateWithMagicAuth(
    code: String,
    email: String,
    invitationToken: String? = null,
    ipAddress: String? = null,
    deviceId: String? = null,
    userAgent: String? = null,
    requestOptions: RequestOptions? = null
  ): AuthenticateResponse =
    authenticate(
      grantType = "urn:workos:oauth:grant-type:magic-auth:code",
      requestOptions = requestOptions,
      "code" to code,
      "email" to email,
      "invitation_token" to invitationToken,
      "ip_address" to ipAddress,
      "device_id" to deviceId,
      "user_agent" to userAgent
    )

  /**
   * Coroutine-aware variant of [authenticateWithMagicAuth]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [authenticateWithMagicAuth] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("authenticateWithMagicAuthSuspend")
  suspend fun authenticateWithMagicAuthSuspend(
    code: String,
    email: String,
    invitationToken: String? = null,
    ipAddress: String? = null,
    deviceId: String? = null,
    userAgent: String? = null,
    requestOptions: RequestOptions? = null
  ): AuthenticateResponse =
    withContext(Dispatchers.IO) {
      authenticateWithMagicAuth(code, email, invitationToken, ipAddress, deviceId, userAgent, requestOptions)
    }

  /**
   * Authenticate
   *
   * @param code the code of the request.
   * @param pendingAuthenticationToken the pending authentication token of the request.
   * @param ipAddress the ip address of the request.
   * @param deviceId the device id of the request.
   * @param userAgent the user agent of the request.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   * @return the AuthenticateResponse
   */
  @JvmOverloads
  fun authenticateWithEmailVerification(
    code: String,
    pendingAuthenticationToken: String,
    ipAddress: String? = null,
    deviceId: String? = null,
    userAgent: String? = null,
    requestOptions: RequestOptions? = null
  ): AuthenticateResponse =
    authenticate(
      grantType = "urn:workos:oauth:grant-type:email-verification:code",
      requestOptions = requestOptions,
      "code" to code,
      "pending_authentication_token" to pendingAuthenticationToken,
      "ip_address" to ipAddress,
      "device_id" to deviceId,
      "user_agent" to userAgent
    )

  /**
   * Coroutine-aware variant of [authenticateWithEmailVerification]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [authenticateWithEmailVerification] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("authenticateWithEmailVerificationSuspend")
  suspend fun authenticateWithEmailVerificationSuspend(
    code: String,
    pendingAuthenticationToken: String,
    ipAddress: String? = null,
    deviceId: String? = null,
    userAgent: String? = null,
    requestOptions: RequestOptions? = null
  ): AuthenticateResponse =
    withContext(Dispatchers.IO) {
      authenticateWithEmailVerification(code, pendingAuthenticationToken, ipAddress, deviceId, userAgent, requestOptions)
    }

  /**
   * Authenticate
   *
   * @param code the code of the request.
   * @param pendingAuthenticationToken the pending authentication token of the request.
   * @param authenticationChallengeId the authentication challenge id of the request.
   * @param ipAddress the ip address of the request.
   * @param deviceId the device id of the request.
   * @param userAgent the user agent of the request.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   * @return the AuthenticateResponse
   */
  @JvmOverloads
  fun authenticateWithTotp(
    code: String,
    pendingAuthenticationToken: String,
    authenticationChallengeId: String,
    ipAddress: String? = null,
    deviceId: String? = null,
    userAgent: String? = null,
    requestOptions: RequestOptions? = null
  ): AuthenticateResponse =
    authenticate(
      grantType = "urn:workos:oauth:grant-type:mfa-totp",
      requestOptions = requestOptions,
      "code" to code,
      "pending_authentication_token" to pendingAuthenticationToken,
      "authentication_challenge_id" to authenticationChallengeId,
      "ip_address" to ipAddress,
      "device_id" to deviceId,
      "user_agent" to userAgent
    )

  /**
   * Coroutine-aware variant of [authenticateWithTotp]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [authenticateWithTotp] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("authenticateWithTotpSuspend")
  suspend fun authenticateWithTotpSuspend(
    code: String,
    pendingAuthenticationToken: String,
    authenticationChallengeId: String,
    ipAddress: String? = null,
    deviceId: String? = null,
    userAgent: String? = null,
    requestOptions: RequestOptions? = null
  ): AuthenticateResponse =
    withContext(Dispatchers.IO) {
      authenticateWithTotp(code, pendingAuthenticationToken, authenticationChallengeId, ipAddress, deviceId, userAgent, requestOptions)
    }

  /**
   * Authenticate
   *
   * @param pendingAuthenticationToken the pending authentication token of the request.
   * @param organizationId the organization id of the request.
   * @param ipAddress the ip address of the request.
   * @param deviceId the device id of the request.
   * @param userAgent the user agent of the request.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   * @return the AuthenticateResponse
   */
  @JvmOverloads
  fun authenticateWithOrganizationSelection(
    pendingAuthenticationToken: String,
    organizationId: String,
    ipAddress: String? = null,
    deviceId: String? = null,
    userAgent: String? = null,
    requestOptions: RequestOptions? = null
  ): AuthenticateResponse =
    authenticate(
      grantType = "urn:workos:oauth:grant-type:organization-selection",
      requestOptions = requestOptions,
      "pending_authentication_token" to pendingAuthenticationToken,
      "organization_id" to organizationId,
      "ip_address" to ipAddress,
      "device_id" to deviceId,
      "user_agent" to userAgent
    )

  /**
   * Coroutine-aware variant of [authenticateWithOrganizationSelection]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [authenticateWithOrganizationSelection] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("authenticateWithOrganizationSelectionSuspend")
  suspend fun authenticateWithOrganizationSelectionSuspend(
    pendingAuthenticationToken: String,
    organizationId: String,
    ipAddress: String? = null,
    deviceId: String? = null,
    userAgent: String? = null,
    requestOptions: RequestOptions? = null
  ): AuthenticateResponse =
    withContext(Dispatchers.IO) {
      authenticateWithOrganizationSelection(pendingAuthenticationToken, organizationId, ipAddress, deviceId, userAgent, requestOptions)
    }

  /**
   * Authenticate
   *
   * @param deviceCode the device code of the request.
   * @param ipAddress the ip address of the request.
   * @param deviceId the device id of the request.
   * @param userAgent the user agent of the request.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   * @return the AuthenticateResponse
   */
  @JvmOverloads
  fun authenticateWithDeviceCode(
    deviceCode: String,
    ipAddress: String? = null,
    deviceId: String? = null,
    userAgent: String? = null,
    requestOptions: RequestOptions? = null
  ): AuthenticateResponse {
    val body =
      bodyOf(
        "device_code" to deviceCode,
        "ip_address" to ipAddress,
        "device_id" to deviceId,
        "user_agent" to userAgent,
        "grant_type" to "urn:ietf:params:oauth:grant-type:device_code",
        "client_id" to workos.clientId
      )
    val config =
      RequestConfig(
        method = "POST",
        path = "/user_management/authenticate",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, AuthenticateResponse::class.java)
  }

  /**
   * Coroutine-aware variant of [authenticateWithDeviceCode]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [authenticateWithDeviceCode] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("authenticateWithDeviceCodeSuspend")
  suspend fun authenticateWithDeviceCodeSuspend(
    deviceCode: String,
    ipAddress: String? = null,
    deviceId: String? = null,
    userAgent: String? = null,
    requestOptions: RequestOptions? = null
  ): AuthenticateResponse =
    withContext(Dispatchers.IO) {
      authenticateWithDeviceCode(deviceCode, ipAddress, deviceId, userAgent, requestOptions)
    }

  /**
   * Get device authorization URL
   *
   * Initiates the CLI Auth flow by requesting a device code and verification URLs. This endpoint implements the OAuth 2.0 Device Authorization Flow ([RFC 8628](https://datatracker.ietf.org/doc/html/rfc8628)) and is designed for command-line applications or other devices with limited input capabilities.
   *
   * @param clientId The WorkOS client ID for your application.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the DeviceAuthorizationResponse
   */
  @JvmOverloads
  fun createDevice(
    clientId: String,
    requestOptions: RequestOptions? = null
  ): DeviceAuthorizationResponse {
    val body =
      bodyOf(
        "client_id" to clientId
      )
    val config =
      RequestConfig(
        method = "POST",
        path = "/user_management/authorize/device",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, DeviceAuthorizationResponse::class.java)
  }

  /**
   * Coroutine-aware variant of [createDevice]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [createDevice] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("createDeviceSuspend")
  suspend fun createDeviceSuspend(
    clientId: String,
    requestOptions: RequestOptions? = null
  ): DeviceAuthorizationResponse =
    withContext(Dispatchers.IO) {
      createDevice(clientId, requestOptions)
    }

  /**
   * Revoke Session
   *
   * Revoke a [user session](https://workos.com/docs/reference/authkit/session).
   *
   * @param sessionId The ID of the session to revoke. This can be extracted from the `sid` claim of the access token.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   */
  @JvmOverloads
  fun revokeSession(
    sessionId: String,
    requestOptions: RequestOptions? = null
  ) {
    val body =
      bodyOf(
        "session_id" to sessionId
      )
    val config =
      RequestConfig(
        method = "POST",
        path = "/user_management/sessions/revoke",
        body = body,
        requestOptions = requestOptions
      )
    workos.baseClient.requestVoid(config)
  }

  /**
   * Coroutine-aware variant of [revokeSession]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [revokeSession] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("revokeSessionSuspend")
  suspend fun revokeSessionSuspend(
    sessionId: String,
    requestOptions: RequestOptions? = null
  ) = withContext(Dispatchers.IO) {
    revokeSession(sessionId, requestOptions)
  }

  /**
   * Create a CORS origin
   *
   * Creates a new CORS origin for the current environment. CORS origins allow browser-based applications to make requests to the WorkOS API.
   *
   * @param origin The origin URL to allow for CORS requests.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the CorsOriginResponse
   */
  @JvmOverloads
  fun createCorsOrigin(
    origin: String,
    requestOptions: RequestOptions? = null
  ): CorsOriginResponse {
    val body =
      bodyOf(
        "origin" to origin
      )
    val config =
      RequestConfig(
        method = "POST",
        path = "/user_management/cors_origins",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, CorsOriginResponse::class.java)
  }

  /**
   * Coroutine-aware variant of [createCorsOrigin]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [createCorsOrigin] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("createCorsOriginSuspend")
  suspend fun createCorsOriginSuspend(
    origin: String,
    requestOptions: RequestOptions? = null
  ): CorsOriginResponse =
    withContext(Dispatchers.IO) {
      createCorsOrigin(origin, requestOptions)
    }

  /**
   * Get an email verification code
   *
   * Get the details of an existing email verification code that can be used to send an email to a user for verification.
   *
   * @param id The ID of the email verification code.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the EmailVerification
   */
  @JvmOverloads
  fun getEmailVerification(
    id: String,
    requestOptions: RequestOptions? = null
  ): EmailVerification {
    val config =
      RequestConfig(
        method = "GET",
        path = "/user_management/email_verification/${encodePathSegment(id)}",
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, EmailVerification::class.java)
  }

  /**
   * Coroutine-aware variant of [getEmailVerification]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [getEmailVerification] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("getEmailVerificationSuspend")
  suspend fun getEmailVerificationSuspend(
    id: String,
    requestOptions: RequestOptions? = null
  ): EmailVerification =
    withContext(Dispatchers.IO) {
      getEmailVerification(id, requestOptions)
    }

  /**
   * Create a password reset token
   *
   * Creates a one-time token that can be used to reset a user's password.
   *
   * @param email The email address of the user requesting a password reset.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the PasswordReset
   */
  @JvmOverloads
  fun resetPassword(
    email: String,
    requestOptions: RequestOptions? = null
  ): PasswordReset {
    val body =
      bodyOf(
        "email" to email
      )
    val config =
      RequestConfig(
        method = "POST",
        path = "/user_management/password_reset",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, PasswordReset::class.java)
  }

  /**
   * Coroutine-aware variant of [resetPassword]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [resetPassword] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("resetPasswordSuspend")
  suspend fun resetPasswordSuspend(
    email: String,
    requestOptions: RequestOptions? = null
  ): PasswordReset =
    withContext(Dispatchers.IO) {
      resetPassword(email, requestOptions)
    }

  /**
   * Reset the password
   *
   * Sets a new password using the `token` query parameter from the link that the user received. Successfully resetting the password will verify a user's email, if it hasn't been verified yet.
   *
   * @param token The password reset token.
   * @param newPassword The new password to set for the user.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the ResetPasswordResponse
   */
  @JvmOverloads
  fun confirmPasswordReset(
    token: String,
    newPassword: String,
    requestOptions: RequestOptions? = null
  ): ResetPasswordResponse {
    val body =
      bodyOf(
        "token" to token,
        "new_password" to newPassword
      )
    val config =
      RequestConfig(
        method = "POST",
        path = "/user_management/password_reset/confirm",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, ResetPasswordResponse::class.java)
  }

  /**
   * Coroutine-aware variant of [confirmPasswordReset]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [confirmPasswordReset] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("confirmPasswordResetSuspend")
  suspend fun confirmPasswordResetSuspend(
    token: String,
    newPassword: String,
    requestOptions: RequestOptions? = null
  ): ResetPasswordResponse =
    withContext(Dispatchers.IO) {
      confirmPasswordReset(token, newPassword, requestOptions)
    }

  /**
   * Get a password reset token
   *
   * Get the details of an existing password reset token that can be used to reset a user's password.
   *
   * @param id The ID of the password reset token.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the PasswordReset
   */
  @JvmOverloads
  fun getPasswordReset(
    id: String,
    requestOptions: RequestOptions? = null
  ): PasswordReset {
    val config =
      RequestConfig(
        method = "GET",
        path = "/user_management/password_reset/${encodePathSegment(id)}",
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, PasswordReset::class.java)
  }

  /**
   * Coroutine-aware variant of [getPasswordReset]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [getPasswordReset] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("getPasswordResetSuspend")
  suspend fun getPasswordResetSuspend(
    id: String,
    requestOptions: RequestOptions? = null
  ): PasswordReset =
    withContext(Dispatchers.IO) {
      getPasswordReset(id, requestOptions)
    }

  /**
   * List users
   *
   * Get a list of all of your existing users matching the criteria specified.
   *
   * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
   * @param after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
   * @param limit Upper limit on the number of objects to return, between `1` and `100`.
   * @param order the order to return records in. See [PaginationOrder].
   * @param organization **Deprecated.** Filter users by the organization they are a member of. Deprecated in favor of `organization_id`.
   * @param organizationId Filter users by the organization they are a member of.
   * @param email Filter users by their email address.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return a [com.workos.common.http.Page] of results
   */
  @JvmOverloads
  fun list(
    before: String? = null,
    after: String? = null,
    limit: Int? = null,
    order: PaginationOrder? = null,
    organization: String? = null,
    organizationId: String? = null,
    email: String? = null,
    requestOptions: RequestOptions? = null
  ): Page<User> {
    val itemType = object : TypeReference<User>() {}
    return workos.baseClient.requestPage(
      method = "GET",
      path = "/user_management/users",
      itemType = itemType,
      requestOptions = requestOptions,
      before = before,
      after = after
    ) {
      limit?.let { add("limit" to it.toString()) }
      order?.let { add("order" to it.value) }
      addIfNotNull("organization", organization)
      addIfNotNull("organization_id", organizationId)
      addIfNotNull("email", email)
    }
  }

  /**
   * Coroutine-aware variant of [list]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [list] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("listSuspend")
  suspend fun listSuspend(
    before: String? = null,
    after: String? = null,
    limit: Int? = null,
    order: PaginationOrder? = null,
    organization: String? = null,
    organizationId: String? = null,
    email: String? = null,
    requestOptions: RequestOptions? = null
  ): Page<User> =
    withContext(Dispatchers.IO) {
      list(before, after, limit, order, organization, organizationId, email, requestOptions)
    }

  /**
   * Create a user
   *
   * Create a new user in the current environment.
   *
   * @param email The email address of the user.
   * @param firstName The first name of the user.
   * @param lastName The last name of the user.
   * @param name The user's full name.
   * @param emailVerified Whether the user's email has been verified.
   * @param metadata Object containing metadata key/value pairs associated with the user.
   * @param externalId The external ID of the user.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the User
   */
  @JvmOverloads
  fun create(
    createUserPassword: CreateUserPassword? = null,
    email: String,
    firstName: String? = null,
    lastName: String? = null,
    name: String? = null,
    emailVerified: Boolean? = null,
    metadata: Map<String, String>? = null,
    externalId: String? = null,
    requestOptions: RequestOptions? = null
  ): User {
    val body =
      bodyOf(
        "email" to email,
        "first_name" to firstName,
        "last_name" to lastName,
        "name" to name,
        "email_verified" to emailVerified,
        "metadata" to metadata,
        "external_id" to externalId
      )
    if (createUserPassword != null) {
      when (createUserPassword) {
        is CreateUserPassword.Plaintext -> body["password"] = createUserPassword.password
        is CreateUserPassword.Hashed -> {
          body["password_hash"] = createUserPassword.hash
          body["password_hash_type"] = createUserPassword.hashType
        }
      }
    }
    val config =
      RequestConfig(
        method = "POST",
        path = "/user_management/users",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, User::class.java)
  }

  /**
   * Coroutine-aware variant of [create]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [create] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("createSuspend")
  suspend fun createSuspend(
    createUserPassword: CreateUserPassword? = null,
    email: String,
    firstName: String? = null,
    lastName: String? = null,
    name: String? = null,
    emailVerified: Boolean? = null,
    metadata: Map<String, String>? = null,
    externalId: String? = null,
    requestOptions: RequestOptions? = null
  ): User =
    withContext(Dispatchers.IO) {
      create(createUserPassword, email, firstName, lastName, name, emailVerified, metadata, externalId, requestOptions)
    }

  /**
   * Get a user by external ID
   *
   * Get the details of an existing user by an [external identifier](https://workos.com/docs/authkit/metadata/external-identifiers).
   *
   * @param externalId The external ID of the user.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the User
   */
  @JvmOverloads
  fun getByExternalId(
    externalId: String,
    requestOptions: RequestOptions? = null
  ): User {
    val config =
      RequestConfig(
        method = "GET",
        path = "/user_management/users/external_id/${encodePathSegment(externalId)}",
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, User::class.java)
  }

  /**
   * Coroutine-aware variant of [getByExternalId]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [getByExternalId] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("getByExternalIdSuspend")
  suspend fun getByExternalIdSuspend(
    externalId: String,
    requestOptions: RequestOptions? = null
  ): User =
    withContext(Dispatchers.IO) {
      getByExternalId(externalId, requestOptions)
    }

  /**
   * Get a user
   *
   * Get the details of an existing user.
   *
   * @param id The unique ID of the user.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the User
   */
  @JvmOverloads
  fun get(
    id: String,
    requestOptions: RequestOptions? = null
  ): User {
    val config =
      RequestConfig(
        method = "GET",
        path = "/user_management/users/${encodePathSegment(id)}",
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, User::class.java)
  }

  /**
   * Coroutine-aware variant of [get]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [get] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("getSuspend")
  suspend fun getSuspend(
    id: String,
    requestOptions: RequestOptions? = null
  ): User =
    withContext(Dispatchers.IO) {
      get(id, requestOptions)
    }

  /**
   * Update a user
   *
   * Updates properties of a user. The omitted properties will be left unchanged.
   *
   * @param id The unique ID of the user.
   * @param email The email address of the user.
   * @param firstName The first name of the user.
   * @param lastName The last name of the user.
   * @param name The user's full name.
   * @param emailVerified Whether the user's email has been verified.
   * @param metadata Object containing metadata key/value pairs associated with the user.
   * @param externalId The external ID of the user.
   * @param locale The user's preferred locale.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the User
   */
  @JvmOverloads
  fun update(
    id: String,
    createUserPassword: CreateUserPassword? = null,
    email: String? = null,
    firstName: String? = null,
    lastName: String? = null,
    name: String? = null,
    emailVerified: Boolean? = null,
    metadata: Map<String, String>? = null,
    externalId: String? = null,
    locale: String? = null,
    requestOptions: RequestOptions? = null
  ): User {
    val body =
      bodyOf(
        "email" to email,
        "first_name" to firstName,
        "last_name" to lastName,
        "name" to name,
        "email_verified" to emailVerified,
        "metadata" to metadata,
        "external_id" to externalId,
        "locale" to locale
      )
    if (createUserPassword != null) {
      when (createUserPassword) {
        is CreateUserPassword.Plaintext -> body["password"] = createUserPassword.password
        is CreateUserPassword.Hashed -> {
          body["password_hash"] = createUserPassword.hash
          body["password_hash_type"] = createUserPassword.hashType
        }
      }
    }
    val config =
      RequestConfig(
        method = "PUT",
        path = "/user_management/users/${encodePathSegment(id)}",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, User::class.java)
  }

  /**
   * Coroutine-aware variant of [update]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [update] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("updateSuspend")
  suspend fun updateSuspend(
    id: String,
    createUserPassword: CreateUserPassword? = null,
    email: String? = null,
    firstName: String? = null,
    lastName: String? = null,
    name: String? = null,
    emailVerified: Boolean? = null,
    metadata: Map<String, String>? = null,
    externalId: String? = null,
    locale: String? = null,
    requestOptions: RequestOptions? = null
  ): User =
    withContext(Dispatchers.IO) {
      update(id, createUserPassword, email, firstName, lastName, name, emailVerified, metadata, externalId, locale, requestOptions)
    }

  /**
   * Delete a user
   *
   * Permanently deletes a user in the current environment. It cannot be undone.
   *
   * @param id The unique ID of the user.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   */
  @JvmOverloads
  fun delete(
    id: String,
    requestOptions: RequestOptions? = null
  ) {
    val config =
      RequestConfig(
        method = "DELETE",
        path = "/user_management/users/${encodePathSegment(id)}",
        requestOptions = requestOptions
      )
    workos.baseClient.requestVoid(config)
  }

  /**
   * Coroutine-aware variant of [delete]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [delete] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("deleteSuspend")
  suspend fun deleteSuspend(
    id: String,
    requestOptions: RequestOptions? = null
  ) = withContext(Dispatchers.IO) {
    delete(id, requestOptions)
  }

  /**
   * Confirm email change
   *
   * Confirms an email change using the one-time code received by the user.
   *
   * @param id The unique ID of the user.
   * @param code The one-time code used to confirm the email change.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the EmailChangeConfirmation
   */
  @JvmOverloads
  fun confirmEmailChange(
    id: String,
    code: String,
    requestOptions: RequestOptions? = null
  ): EmailChangeConfirmation {
    val body =
      bodyOf(
        "code" to code
      )
    val config =
      RequestConfig(
        method = "POST",
        path = "/user_management/users/${encodePathSegment(id)}/email_change/confirm",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, EmailChangeConfirmation::class.java)
  }

  /**
   * Coroutine-aware variant of [confirmEmailChange]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [confirmEmailChange] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("confirmEmailChangeSuspend")
  suspend fun confirmEmailChangeSuspend(
    id: String,
    code: String,
    requestOptions: RequestOptions? = null
  ): EmailChangeConfirmation =
    withContext(Dispatchers.IO) {
      confirmEmailChange(id, code, requestOptions)
    }

  /**
   * Send email change code
   *
   * Sends an email that contains a one-time code used to change a user's email address.
   *
   * @param id The unique ID of the user.
   * @param newEmail The new email address to change to.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the EmailChange
   */
  @JvmOverloads
  fun sendEmailChange(
    id: String,
    newEmail: String,
    requestOptions: RequestOptions? = null
  ): EmailChange {
    val body =
      bodyOf(
        "new_email" to newEmail
      )
    val config =
      RequestConfig(
        method = "POST",
        path = "/user_management/users/${encodePathSegment(id)}/email_change/send",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, EmailChange::class.java)
  }

  /**
   * Coroutine-aware variant of [sendEmailChange]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [sendEmailChange] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("sendEmailChangeSuspend")
  suspend fun sendEmailChangeSuspend(
    id: String,
    newEmail: String,
    requestOptions: RequestOptions? = null
  ): EmailChange =
    withContext(Dispatchers.IO) {
      sendEmailChange(id, newEmail, requestOptions)
    }

  /**
   * Verify email
   *
   * Verifies an email address using the one-time code received by the user.
   *
   * @param id The ID of the user.
   * @param code The one-time email verification code.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the VerifyEmailResponse
   */
  @JvmOverloads
  fun verifyEmail(
    id: String,
    code: String,
    requestOptions: RequestOptions? = null
  ): VerifyEmailResponse {
    val body =
      bodyOf(
        "code" to code
      )
    val config =
      RequestConfig(
        method = "POST",
        path = "/user_management/users/${encodePathSegment(id)}/email_verification/confirm",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, VerifyEmailResponse::class.java)
  }

  /**
   * Coroutine-aware variant of [verifyEmail]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [verifyEmail] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("verifyEmailSuspend")
  suspend fun verifyEmailSuspend(
    id: String,
    code: String,
    requestOptions: RequestOptions? = null
  ): VerifyEmailResponse =
    withContext(Dispatchers.IO) {
      verifyEmail(id, code, requestOptions)
    }

  /**
   * Send verification email
   *
   * Sends an email that contains a one-time code used to verify a user's email address.
   *
   * @param id The ID of the user.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the SendVerificationEmailResponse
   */
  @JvmOverloads
  fun sendVerificationEmail(
    id: String,
    requestOptions: RequestOptions? = null
  ): SendVerificationEmailResponse {
    val body = linkedMapOf<String, Any?>()
    val config =
      RequestConfig(
        method = "POST",
        path = "/user_management/users/${encodePathSegment(id)}/email_verification/send",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, SendVerificationEmailResponse::class.java)
  }

  /**
   * Coroutine-aware variant of [sendVerificationEmail]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [sendVerificationEmail] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("sendVerificationEmailSuspend")
  suspend fun sendVerificationEmailSuspend(
    id: String,
    requestOptions: RequestOptions? = null
  ): SendVerificationEmailResponse =
    withContext(Dispatchers.IO) {
      sendVerificationEmail(id, requestOptions)
    }

  /**
   * Get user identities
   *
   * Get a list of identities associated with the user. A user can have multiple associated identities after going through [identity linking](https://workos.com/docs/authkit/identity-linking). Currently only OAuth identities are supported. More provider types may be added in the future.
   *
   * @param id The unique ID of the user.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the list of UserIdentitiesGetItem
   */
  @JvmOverloads
  fun getIdentities(
    id: String,
    requestOptions: RequestOptions? = null
  ): List<UserIdentitiesGetItem> {
    val config =
      RequestConfig(
        method = "GET",
        path = "/user_management/users/${encodePathSegment(id)}/identities",
        requestOptions = requestOptions
      )
    val responseType = object : TypeReference<List<UserIdentitiesGetItem>>() {}
    return workos.baseClient.request(config, responseType)
  }

  /**
   * Coroutine-aware variant of [getIdentities]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [getIdentities] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("getIdentitiesSuspend")
  suspend fun getIdentitiesSuspend(
    id: String,
    requestOptions: RequestOptions? = null
  ): List<UserIdentitiesGetItem> =
    withContext(Dispatchers.IO) {
      getIdentities(id, requestOptions)
    }

  /**
   * List sessions
   *
   * Get a list of all active sessions for a specific user.
   *
   * @param id The ID of the user.
   * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
   * @param after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
   * @param limit Upper limit on the number of objects to return, between `1` and `100`.
   * @param order the order to return records in. See [PaginationOrder].
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return a [com.workos.common.http.Page] of results
   */
  @JvmOverloads
  fun listSessions(
    id: String,
    before: String? = null,
    after: String? = null,
    limit: Int? = null,
    order: PaginationOrder? = null,
    requestOptions: RequestOptions? = null
  ): Page<UserSessionsListItem> {
    val itemType = object : TypeReference<UserSessionsListItem>() {}
    return workos.baseClient.requestPage(
      method = "GET",
      path = "/user_management/users/${encodePathSegment(id)}/sessions",
      itemType = itemType,
      requestOptions = requestOptions,
      before = before,
      after = after
    ) {
      limit?.let { add("limit" to it.toString()) }
      order?.let { add("order" to it.value) }
    }
  }

  /**
   * Coroutine-aware variant of [listSessions]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [listSessions] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("listSessionsSuspend")
  suspend fun listSessionsSuspend(
    id: String,
    before: String? = null,
    after: String? = null,
    limit: Int? = null,
    order: PaginationOrder? = null,
    requestOptions: RequestOptions? = null
  ): Page<UserSessionsListItem> =
    withContext(Dispatchers.IO) {
      listSessions(id, before, after, limit, order, requestOptions)
    }

  /**
   * List invitations
   *
   * Get a list of all of invitations matching the criteria specified.
   *
   * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
   * @param after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
   * @param limit Upper limit on the number of objects to return, between `1` and `100`.
   * @param order the order to return records in. See [PaginationOrder].
   * @param organizationId The ID of the [organization](https://workos.com/docs/reference/organization) that the recipient will join.
   * @param email The email address of the recipient.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return a [com.workos.common.http.Page] of results
   */
  @JvmOverloads
  fun listInvitations(
    before: String? = null,
    after: String? = null,
    limit: Int? = null,
    order: PaginationOrder? = null,
    organizationId: String? = null,
    email: String? = null,
    requestOptions: RequestOptions? = null
  ): Page<UserInvite> {
    val itemType = object : TypeReference<UserInvite>() {}
    return workos.baseClient.requestPage(
      method = "GET",
      path = "/user_management/invitations",
      itemType = itemType,
      requestOptions = requestOptions,
      before = before,
      after = after
    ) {
      limit?.let { add("limit" to it.toString()) }
      order?.let { add("order" to it.value) }
      addIfNotNull("organization_id", organizationId)
      addIfNotNull("email", email)
    }
  }

  /**
   * Coroutine-aware variant of [listInvitations]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [listInvitations] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("listInvitationsSuspend")
  suspend fun listInvitationsSuspend(
    before: String? = null,
    after: String? = null,
    limit: Int? = null,
    order: PaginationOrder? = null,
    organizationId: String? = null,
    email: String? = null,
    requestOptions: RequestOptions? = null
  ): Page<UserInvite> =
    withContext(Dispatchers.IO) {
      listInvitations(before, after, limit, order, organizationId, email, requestOptions)
    }

  /**
   * Send an invitation
   *
   * Sends an invitation email to the recipient.
   *
   * @param email The email address of the recipient.
   * @param organizationId The ID of the [organization](https://workos.com/docs/reference/organization) that the recipient will join.
   * @param roleSlug The [role](https://workos.com/docs/authkit/roles) that the recipient will receive when they join the organization in the invitation.
   * @param expiresInDays How many days the invitations will be valid for. Must be between 1 and 30 days. Defaults to 7 days if not specified.
   * @param inviterUserId The ID of the [user](https://workos.com/docs/reference/authkit/user) who invites the recipient. The invitation email will mention the name of this user.
   * @param locale The locale to use when rendering the invitation email. See [supported locales](https://workos.com/docs/authkit/hosted-ui/localization).
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the UserInvite
   */
  @JvmOverloads
  fun sendInvitation(
    email: String,
    organizationId: String? = null,
    roleSlug: String? = null,
    expiresInDays: Long? = null,
    inviterUserId: String? = null,
    locale: CreateUserInviteOptionsLocale? = null,
    requestOptions: RequestOptions? = null
  ): UserInvite {
    val body =
      bodyOf(
        "email" to email,
        "organization_id" to organizationId,
        "role_slug" to roleSlug,
        "expires_in_days" to expiresInDays,
        "inviter_user_id" to inviterUserId,
        "locale" to locale
      )
    val config =
      RequestConfig(
        method = "POST",
        path = "/user_management/invitations",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, UserInvite::class.java)
  }

  /**
   * Coroutine-aware variant of [sendInvitation]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [sendInvitation] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("sendInvitationSuspend")
  suspend fun sendInvitationSuspend(
    email: String,
    organizationId: String? = null,
    roleSlug: String? = null,
    expiresInDays: Long? = null,
    inviterUserId: String? = null,
    locale: CreateUserInviteOptionsLocale? = null,
    requestOptions: RequestOptions? = null
  ): UserInvite =
    withContext(Dispatchers.IO) {
      sendInvitation(email, organizationId, roleSlug, expiresInDays, inviterUserId, locale, requestOptions)
    }

  /**
   * Find an invitation by token
   *
   * Retrieve an existing invitation using the token.
   *
   * @param token The token used to accept the invitation.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the UserInvite
   */
  @JvmOverloads
  fun findInvitationByToken(
    token: String,
    requestOptions: RequestOptions? = null
  ): UserInvite {
    val config =
      RequestConfig(
        method = "GET",
        path = "/user_management/invitations/by_token/${encodePathSegment(token)}",
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, UserInvite::class.java)
  }

  /**
   * Coroutine-aware variant of [findInvitationByToken]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [findInvitationByToken] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("findInvitationByTokenSuspend")
  suspend fun findInvitationByTokenSuspend(
    token: String,
    requestOptions: RequestOptions? = null
  ): UserInvite =
    withContext(Dispatchers.IO) {
      findInvitationByToken(token, requestOptions)
    }

  /**
   * Get an invitation
   *
   * Get the details of an existing invitation.
   *
   * @param id The unique ID of the invitation.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the UserInvite
   */
  @JvmOverloads
  fun getInvitation(
    id: String,
    requestOptions: RequestOptions? = null
  ): UserInvite {
    val config =
      RequestConfig(
        method = "GET",
        path = "/user_management/invitations/${encodePathSegment(id)}",
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, UserInvite::class.java)
  }

  /**
   * Coroutine-aware variant of [getInvitation]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [getInvitation] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("getInvitationSuspend")
  suspend fun getInvitationSuspend(
    id: String,
    requestOptions: RequestOptions? = null
  ): UserInvite =
    withContext(Dispatchers.IO) {
      getInvitation(id, requestOptions)
    }

  /**
   * Accept an invitation
   *
   * Accepts an invitation and, if linked to an organization, activates the user's membership in that organization.
   *
   * @param id The unique ID of the invitation.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the Invitation
   */
  @JvmOverloads
  fun acceptInvitation(
    id: String,
    requestOptions: RequestOptions? = null
  ): Invitation {
    val body = linkedMapOf<String, Any?>()
    val config =
      RequestConfig(
        method = "POST",
        path = "/user_management/invitations/${encodePathSegment(id)}/accept",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, Invitation::class.java)
  }

  /**
   * Coroutine-aware variant of [acceptInvitation]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [acceptInvitation] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("acceptInvitationSuspend")
  suspend fun acceptInvitationSuspend(
    id: String,
    requestOptions: RequestOptions? = null
  ): Invitation =
    withContext(Dispatchers.IO) {
      acceptInvitation(id, requestOptions)
    }

  /**
   * Resend an invitation
   *
   * Resends an invitation email to the recipient. The invitation must be in a pending state.
   *
   * @param id The unique ID of the invitation.
   * @param locale The locale to use when rendering the invitation email. See [supported locales](https://workos.com/docs/authkit/hosted-ui/localization).
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the UserInvite
   */
  @JvmOverloads
  fun resendInvitation(
    id: String,
    locale: CreateUserInviteOptionsLocale? = null,
    requestOptions: RequestOptions? = null
  ): UserInvite {
    val body =
      bodyOf(
        "locale" to locale
      )
    val config =
      RequestConfig(
        method = "POST",
        path = "/user_management/invitations/${encodePathSegment(id)}/resend",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, UserInvite::class.java)
  }

  /**
   * Coroutine-aware variant of [resendInvitation]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [resendInvitation] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("resendInvitationSuspend")
  suspend fun resendInvitationSuspend(
    id: String,
    locale: CreateUserInviteOptionsLocale? = null,
    requestOptions: RequestOptions? = null
  ): UserInvite =
    withContext(Dispatchers.IO) {
      resendInvitation(id, locale, requestOptions)
    }

  /**
   * Revoke an invitation
   *
   * Revokes an existing invitation.
   *
   * @param id The unique ID of the invitation.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the Invitation
   */
  @JvmOverloads
  fun revokeInvitation(
    id: String,
    requestOptions: RequestOptions? = null
  ): Invitation {
    val body = linkedMapOf<String, Any?>()
    val config =
      RequestConfig(
        method = "POST",
        path = "/user_management/invitations/${encodePathSegment(id)}/revoke",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, Invitation::class.java)
  }

  /**
   * Coroutine-aware variant of [revokeInvitation]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [revokeInvitation] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("revokeInvitationSuspend")
  suspend fun revokeInvitationSuspend(
    id: String,
    requestOptions: RequestOptions? = null
  ): Invitation =
    withContext(Dispatchers.IO) {
      revokeInvitation(id, requestOptions)
    }

  /**
   * Get JWT template
   *
   * Get the JWT template for the current environment.
   *
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the JWTTemplateResponse
   */
  @JvmOverloads
  fun listJWTTemplate(requestOptions: RequestOptions? = null): JWTTemplateResponse {
    val config =
      RequestConfig(
        method = "GET",
        path = "/user_management/jwt_template",
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, JWTTemplateResponse::class.java)
  }

  /**
   * Coroutine-aware variant of [listJWTTemplate]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [listJWTTemplate] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("listJWTTemplateSuspend")
  suspend fun listJWTTemplateSuspend(requestOptions: RequestOptions? = null): JWTTemplateResponse =
    withContext(Dispatchers.IO) {
      listJWTTemplate(requestOptions)
    }

  /**
   * Update JWT template
   *
   * Update the JWT template for the current environment.
   *
   * @param content The JWT template content as a Liquid template string.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the JWTTemplateResponse
   */
  @JvmOverloads
  fun updateJWTTemplate(
    content: String,
    requestOptions: RequestOptions? = null
  ): JWTTemplateResponse {
    val body =
      bodyOf(
        "content" to content
      )
    val config =
      RequestConfig(
        method = "PUT",
        path = "/user_management/jwt_template",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, JWTTemplateResponse::class.java)
  }

  /**
   * Coroutine-aware variant of [updateJWTTemplate]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [updateJWTTemplate] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("updateJWTTemplateSuspend")
  suspend fun updateJWTTemplateSuspend(
    content: String,
    requestOptions: RequestOptions? = null
  ): JWTTemplateResponse =
    withContext(Dispatchers.IO) {
      updateJWTTemplate(content, requestOptions)
    }

  /**
   * Create a Magic Auth code
   *
   * Creates a one-time authentication code that can be sent to the user's email address. The code expires in 10 minutes. To verify the code, [authenticate the user with Magic Auth](https://workos.com/docs/reference/authkit/authentication/magic-auth).
   *
   * @param email The email address to send the magic code to.
   * @param invitationToken The invitation token to associate with this magic code.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the MagicAuth
   */
  @JvmOverloads
  fun createMagicAuth(
    email: String,
    invitationToken: String? = null,
    requestOptions: RequestOptions? = null
  ): MagicAuth {
    val body =
      bodyOf(
        "email" to email,
        "invitation_token" to invitationToken
      )
    val config =
      RequestConfig(
        method = "POST",
        path = "/user_management/magic_auth",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, MagicAuth::class.java)
  }

  /**
   * Coroutine-aware variant of [createMagicAuth]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [createMagicAuth] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("createMagicAuthSuspend")
  suspend fun createMagicAuthSuspend(
    email: String,
    invitationToken: String? = null,
    requestOptions: RequestOptions? = null
  ): MagicAuth =
    withContext(Dispatchers.IO) {
      createMagicAuth(email, invitationToken, requestOptions)
    }

  /**
   * Get Magic Auth code details
   *
   * Get the details of an existing [Magic Auth](https://workos.com/docs/reference/authkit/magic-auth) code that can be used to send an email to a user for authentication.
   *
   * @param id The unique ID of the Magic Auth code.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the MagicAuth
   */
  @JvmOverloads
  fun getMagicAuth(
    id: String,
    requestOptions: RequestOptions? = null
  ): MagicAuth {
    val config =
      RequestConfig(
        method = "GET",
        path = "/user_management/magic_auth/${encodePathSegment(id)}",
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, MagicAuth::class.java)
  }

  /**
   * Coroutine-aware variant of [getMagicAuth]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [getMagicAuth] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("getMagicAuthSuspend")
  suspend fun getMagicAuthSuspend(
    id: String,
    requestOptions: RequestOptions? = null
  ): MagicAuth =
    withContext(Dispatchers.IO) {
      getMagicAuth(id, requestOptions)
    }

  /**
   * Create a redirect URI
   *
   * Creates a new redirect URI for an application.
   *
   * @param uri The redirect URI to create.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the RedirectUri
   */
  @JvmOverloads
  fun createRedirectUri(
    uri: String,
    requestOptions: RequestOptions? = null
  ): RedirectUri {
    val body =
      bodyOf(
        "uri" to uri
      )
    val config =
      RequestConfig(
        method = "POST",
        path = "/user_management/redirect_uris",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, RedirectUri::class.java)
  }

  /**
   * Coroutine-aware variant of [createRedirectUri]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [createRedirectUri] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("createRedirectUriSuspend")
  suspend fun createRedirectUriSuspend(
    uri: String,
    requestOptions: RequestOptions? = null
  ): RedirectUri =
    withContext(Dispatchers.IO) {
      createRedirectUri(uri, requestOptions)
    }

  /**
   * List authorized applications
   *
   * Get a list of all Connect applications that the user has authorized.
   *
   * @param userId The ID of the user.
   * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
   * @param after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
   * @param limit Upper limit on the number of objects to return, between `1` and `100`.
   * @param order the order to return records in. See [PaginationOrder].
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return a [com.workos.common.http.Page] of results
   */
  @JvmOverloads
  fun listAuthorizedApplications(
    userId: String,
    before: String? = null,
    after: String? = null,
    limit: Int? = null,
    order: PaginationOrder? = null,
    requestOptions: RequestOptions? = null
  ): Page<AuthorizedConnectApplicationListData> {
    val itemType = object : TypeReference<AuthorizedConnectApplicationListData>() {}
    return workos.baseClient.requestPage(
      method = "GET",
      path = "/user_management/users/${encodePathSegment(userId)}/authorized_applications",
      itemType = itemType,
      requestOptions = requestOptions,
      before = before,
      after = after
    ) {
      limit?.let { add("limit" to it.toString()) }
      order?.let { add("order" to it.value) }
    }
  }

  /**
   * Coroutine-aware variant of [listAuthorizedApplications]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [listAuthorizedApplications] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("listAuthorizedApplicationsSuspend")
  suspend fun listAuthorizedApplicationsSuspend(
    userId: String,
    before: String? = null,
    after: String? = null,
    limit: Int? = null,
    order: PaginationOrder? = null,
    requestOptions: RequestOptions? = null
  ): Page<AuthorizedConnectApplicationListData> =
    withContext(Dispatchers.IO) {
      listAuthorizedApplications(userId, before, after, limit, order, requestOptions)
    }

  /**
   * Delete an authorized application
   *
   * Delete an existing Authorized Connect Application.
   *
   * @param userId The ID of the user.
   * @param applicationId The ID or client ID of the application.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   */
  @JvmOverloads
  fun deleteAuthorizedApplication(
    userId: String,
    applicationId: String,
    requestOptions: RequestOptions? = null
  ) {
    val config =
      RequestConfig(
        method = "DELETE",
        path = "/user_management/users/${encodePathSegment(userId)}/authorized_applications/${encodePathSegment(applicationId)}",
        requestOptions = requestOptions
      )
    workos.baseClient.requestVoid(config)
  }

  /**
   * Coroutine-aware variant of [deleteAuthorizedApplication]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [deleteAuthorizedApplication] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("deleteAuthorizedApplicationSuspend")
  suspend fun deleteAuthorizedApplicationSuspend(
    userId: String,
    applicationId: String,
    requestOptions: RequestOptions? = null
  ) = withContext(Dispatchers.IO) {
    deleteAuthorizedApplication(userId, applicationId, requestOptions)
  }

  /**
   * List API keys for a user
   *
   * Get a list of API keys owned by a specific user.
   *
   * @param userId Unique identifier of the user.
   * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
   * @param after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
   * @param limit Upper limit on the number of objects to return, between `1` and `100`.
   * @param order Order the results by the creation time.
   * @param organizationId The ID of the organization to filter user API keys by. When provided, only API keys created against that organization membership are returned.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return a [com.workos.common.http.Page] of results
   */
  @JvmOverloads
  fun listApiKeys(
    userId: String,
    before: String? = null,
    after: String? = null,
    limit: Int? = null,
    order: PaginationOrder? = null,
    organizationId: String? = null,
    requestOptions: RequestOptions? = null
  ): Page<UserApiKey> {
    val itemType = object : TypeReference<UserApiKey>() {}
    return workos.baseClient.requestPage(
      method = "GET",
      path = "/user_management/users/${encodePathSegment(userId)}/api_keys",
      itemType = itemType,
      requestOptions = requestOptions,
      before = before,
      after = after
    ) {
      limit?.let { add("limit" to it.toString()) }
      order?.let { add("order" to it.value) }
      addIfNotNull("organization_id", organizationId)
    }
  }

  /**
   * Coroutine-aware variant of [listApiKeys]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [listApiKeys] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("listApiKeysSuspend")
  suspend fun listApiKeysSuspend(
    userId: String,
    before: String? = null,
    after: String? = null,
    limit: Int? = null,
    order: PaginationOrder? = null,
    organizationId: String? = null,
    requestOptions: RequestOptions? = null
  ): Page<UserApiKey> =
    withContext(Dispatchers.IO) {
      listApiKeys(userId, before, after, limit, order, organizationId, requestOptions)
    }

  /**
   * Create an API key for a user
   *
   * Create a new API key owned by a user. The user must have an active membership in the specified organization.
   *
   * @param userId Unique identifier of the user.
   * @param name A descriptive name for the API key.
   * @param organizationId The ID of the organization the user API key is associated with. The user must have an active membership in this organization.
   * @param permissions The permission slugs to assign to the API key. Each permission must be enabled for user API keys.
   * @param expiresAt The timestamp when the API key should expire. Must be a future timestamp. If omitted, the key does not expire.
   * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
   *
   * @return the UserApiKeyWithValue
   */
  @JvmOverloads
  fun createApiKey(
    userId: String,
    name: String,
    organizationId: String,
    permissions: List<String>? = null,
    expiresAt: OffsetDateTime? = null,
    requestOptions: RequestOptions? = null
  ): UserApiKeyWithValue {
    val body =
      bodyOf(
        "name" to name,
        "organization_id" to organizationId,
        "permissions" to permissions,
        "expires_at" to expiresAt
      )
    val config =
      RequestConfig(
        method = "POST",
        path = "/user_management/users/${encodePathSegment(userId)}/api_keys",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, UserApiKeyWithValue::class.java)
  }

  /**
   * Coroutine-aware variant of [createApiKey]. Use this from
   * a `suspend` function or coroutine scope.
   *
   * Delegates to the blocking [createApiKey] under
   * `withContext(Dispatchers.IO)`, so this is safe to call from any
   * coroutine dispatcher (including `Dispatchers.Main`).
   */
  @JvmName("createApiKeySuspend")
  suspend fun createApiKeySuspend(
    userId: String,
    name: String,
    organizationId: String,
    permissions: List<String>? = null,
    expiresAt: OffsetDateTime? = null,
    requestOptions: RequestOptions? = null
  ): UserApiKeyWithValue =
    withContext(Dispatchers.IO) {
      createApiKey(userId, name, organizationId, permissions, expiresAt, requestOptions)
    }
}
