// This file is auto-generated by oagen. Do not edit.

package com.workos.apikeys

import com.github.tomakehurst.wiremock.client.WireMock.matchingJsonPath
import com.github.tomakehurst.wiremock.client.WireMock.postRequestedFor
import com.github.tomakehurst.wiremock.client.WireMock.urlPathMatching
import com.workos.common.exceptions.GenericServerException
import com.workos.common.exceptions.NotFoundException
import com.workos.common.exceptions.RateLimitException
import com.workos.common.exceptions.UnauthorizedException
import com.workos.test.TestBase
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test

class ApiKeysTest : TestBase() {
  private fun api() = ApiKeys(createWorkOSClient())

  @Test
  fun `createValidation returns a typed response`() {
    stubResponse("POST", "/api_keys/validations", 200, "{\"api_key\": null}")
    val result = api().createValidation("sample-arg")
    assertNotNull(result)
    wireMockRule.verify(
      postRequestedFor(urlPathMatching("/api_keys/validations"))
        .withRequestBody(matchingJsonPath("$.value"))
    )
  }

  @Test
  @Disabled("generator: could not synthesize required arguments for delete")
  fun `delete returns a typed response`() {
    // Intentionally empty: the generator could not synthesize required arguments.
  }

  @Test
  fun `listOrganizationApiKeys returns a typed response`() {
    stubResponse("GET", "/organizations/sample-arg/api_keys", 200, "{\"data\": [], \"list_metadata\": {\"before\": null, \"after\": null}}")
    val result = api().listOrganizationApiKeys("sample-arg")
    assertNotNull(result)
  }

  @Test
  fun `createOrganizationApiKey returns a typed response`() {
    stubResponse(
      "POST",
      "/organizations/sample-arg/api_keys",
      200,
      "{\"object\": \"api_key\", \"id\": \"sample\", \"owner\": {\"type\": \"organization\", \"id\": \"sample\"}, \"name\": \"sample\"," +
        " \"obfuscated_value\": \"sample\", \"last_used_at\": null, \"permissions\": [], \"created_at\": \"2024-01-01T00:00:00Z\", " +
        "\"updated_at\": \"2024-01-01T00:00:00Z\", \"value\": \"sample\"}"
    )
    val result = api().createOrganizationApiKey("sample-arg", "sample-arg")
    assertNotNull(result)
    wireMockRule.verify(
      postRequestedFor(urlPathMatching("/organizations/sample-arg/api_keys"))
        .withRequestBody(matchingJsonPath("$.name"))
    )
  }

  @Test
  fun `createValidation translates 401 to UnauthorizedException`() {
    stubResponse("POST", "/api_keys/validations", 401)
    assertThrows(UnauthorizedException::class.java) {
      api().createValidation("sample-arg")
    }
  }

  @Test
  fun `createValidation translates 404 to NotFoundException`() {
    stubResponse("POST", "/api_keys/validations", 404)
    assertThrows(NotFoundException::class.java) {
      api().createValidation("sample-arg")
    }
  }

  @Test
  fun `createValidation translates 429 to RateLimitException`() {
    stubResponse("POST", "/api_keys/validations", 429)
    assertThrows(RateLimitException::class.java) {
      api().createValidation("sample-arg")
    }
  }

  @Test
  fun `createValidation translates 500 to GenericServerException`() {
    stubResponse("POST", "/api_keys/validations", 500)
    assertThrows(GenericServerException::class.java) {
      api().createValidation("sample-arg")
    }
  }
}
