// This file is auto-generated by oagen. Do not edit.

package com.workos.apikeys

import com.github.tomakehurst.wiremock.client.WireMock.aResponse
import com.github.tomakehurst.wiremock.client.WireMock.get
import com.github.tomakehurst.wiremock.client.WireMock.urlPathMatching
import com.workos.common.exceptions.GenericServerException
import com.workos.common.exceptions.NotFoundException
import com.workos.common.exceptions.RateLimitException
import com.workos.common.exceptions.UnauthorizedException
import com.workos.test.TestBase
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Test

class ApiKeysTest : TestBase() {
  private fun api() = ApiKeys(createWorkOSClient())

  @Test
  fun `listOrganizationApiKeys returns a typed response`() {
    wireMockRule.stubFor(
      get(urlPathMatching("/organizations/sample-arg/api_keys"))
        .willReturn(
          aResponse()
            .withStatus(200)
            .withHeader("Content-Type", "application/json")
            .withBody("{\"data\": [], \"list_metadata\": {\"before\": null, \"after\": null}}")
        )
    )
    val result = api().listOrganizationApiKeys("sample-arg")
    assertNotNull(result)
  }

  @Test
  fun `listOrganizationApiKeys translates 401 to UnauthorizedException`() {
    wireMockRule.stubFor(
      get(urlPathMatching("/organizations/sample-arg/api_keys"))
        .willReturn(
          aResponse()
            .withStatus(401)
            .withHeader("Content-Type", "application/json")
            .withBody("{}")
        )
    )
    assertThrows(UnauthorizedException::class.java) {
      api().listOrganizationApiKeys("sample-arg")
    }
  }

  @Test
  fun `listOrganizationApiKeys translates 404 to NotFoundException`() {
    wireMockRule.stubFor(
      get(urlPathMatching("/organizations/sample-arg/api_keys"))
        .willReturn(
          aResponse()
            .withStatus(404)
            .withHeader("Content-Type", "application/json")
            .withBody("{}")
        )
    )
    assertThrows(NotFoundException::class.java) {
      api().listOrganizationApiKeys("sample-arg")
    }
  }

  @Test
  fun `listOrganizationApiKeys translates 429 to RateLimitException`() {
    wireMockRule.stubFor(
      get(urlPathMatching("/organizations/sample-arg/api_keys"))
        .willReturn(
          aResponse()
            .withStatus(429)
            .withHeader("Content-Type", "application/json")
            .withBody("{}")
        )
    )
    assertThrows(RateLimitException::class.java) {
      api().listOrganizationApiKeys("sample-arg")
    }
  }

  @Test
  fun `listOrganizationApiKeys translates 500 to GenericServerException`() {
    wireMockRule.stubFor(
      get(urlPathMatching("/organizations/sample-arg/api_keys"))
        .willReturn(
          aResponse()
            .withStatus(500)
            .withHeader("Content-Type", "application/json")
            .withBody("{}")
        )
    )
    assertThrows(GenericServerException::class.java) {
      api().listOrganizationApiKeys("sample-arg")
    }
  }
}
