// This file is auto-generated by oagen. Do not edit.

package com.workos.agents

import com.github.tomakehurst.wiremock.client.WireMock.matchingJsonPath
import com.github.tomakehurst.wiremock.client.WireMock.postRequestedFor
import com.github.tomakehurst.wiremock.client.WireMock.urlPathMatching
import com.workos.common.exceptions.GenericServerException
import com.workos.common.exceptions.NotFoundException
import com.workos.common.exceptions.RateLimitException
import com.workos.common.exceptions.UnauthorizedException
import com.workos.test.TestBase
import com.workos.types.AgentAdminValidateCredentialRequestType
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Test

class AgentsTest : TestBase() {
  private fun api() = Agents(createWorkOSClient())

  @Test
  fun `createValidate returns a typed response`() {
    stubResponse("POST", "/agents/credentials/validate", 200, "{\"valid\": false, \"registration_id\": null, \"expires_at\": null}")
    val result =
      api().createValidate(
        AgentAdminValidateCredentialRequestType.values().first { it != AgentAdminValidateCredentialRequestType.Unknown },
        "sample-arg"
      )
    assertNotNull(result)
    assertEquals(false, result.valid)
    wireMockRule.verify(
      postRequestedFor(urlPathMatching("/agents/credentials/validate"))
        .withRequestBody(matchingJsonPath("$.type"))
        .withRequestBody(matchingJsonPath("$.credential"))
    )
  }

  @Test
  fun `getRegistration returns a typed response`() {
    stubResponse(
      "GET",
      "/agents/registrations/sample-arg",
      200,
      "{\"id\": \"sample\", \"agent_identity\": {\"id\": \"sample\", \"userland_user_id\": null, \"created_at\": " +
        "\"2024-01-01T00:00:00Z\", \"updated_at\": \"2024-01-01T00:00:00Z\"}, \"organization_id\": \"sample\", \"status\": " +
        "\"unverified\", \"kind\": \"anonymous\", \"claim\": null, \"created_at\": \"2024-01-01T00:00:00Z\", \"updated_at\": " +
        "\"2024-01-01T00:00:00Z\"}"
    )
    val result = api().getRegistration("sample-arg")
    assertNotNull(result)
    assertEquals("sample", result.id)
    assertEquals("sample", result.organizationId)
  }

  @Test
  fun `createValidate translates 401 to UnauthorizedException`() {
    stubResponse("POST", "/agents/credentials/validate", 401)
    assertThrows(UnauthorizedException::class.java) {
      api().createValidate(
        AgentAdminValidateCredentialRequestType.values().first { it != AgentAdminValidateCredentialRequestType.Unknown },
        "sample-arg"
      )
    }
  }

  @Test
  fun `createValidate translates 404 to NotFoundException`() {
    stubResponse("POST", "/agents/credentials/validate", 404)
    assertThrows(NotFoundException::class.java) {
      api().createValidate(
        AgentAdminValidateCredentialRequestType.values().first { it != AgentAdminValidateCredentialRequestType.Unknown },
        "sample-arg"
      )
    }
  }

  @Test
  fun `createValidate translates 429 to RateLimitException`() {
    stubResponse("POST", "/agents/credentials/validate", 429)
    assertThrows(RateLimitException::class.java) {
      api().createValidate(
        AgentAdminValidateCredentialRequestType.values().first { it != AgentAdminValidateCredentialRequestType.Unknown },
        "sample-arg"
      )
    }
  }

  @Test
  fun `createValidate translates 500 to GenericServerException`() {
    stubResponse("POST", "/agents/credentials/validate", 500)
    assertThrows(GenericServerException::class.java) {
      api().createValidate(
        AgentAdminValidateCredentialRequestType.values().first { it != AgentAdminValidateCredentialRequestType.Unknown },
        "sample-arg"
      )
    }
  }
}
