// This file is auto-generated by oagen. Do not edit.

package com.workos.adminportal

import com.github.tomakehurst.wiremock.client.WireMock.matchingJsonPath
import com.github.tomakehurst.wiremock.client.WireMock.postRequestedFor
import com.github.tomakehurst.wiremock.client.WireMock.urlPathMatching
import com.workos.common.exceptions.GenericServerException
import com.workos.common.exceptions.NotFoundException
import com.workos.common.exceptions.RateLimitException
import com.workos.common.exceptions.UnauthorizedException
import com.workos.test.TestBase
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Test

class AdminPortalTest : TestBase() {
  private fun api() = AdminPortal(createWorkOSClient())

  @Test
  fun `generateLink returns a typed response`() {
    stubResponse("POST", "/portal/generate_link", 200, "{\"link\": \"sample\"}")
    val result = api().generateLink("sample-arg")
    assertNotNull(result)
    assertEquals("sample", result.link)
    wireMockRule.verify(
      postRequestedFor(urlPathMatching("/portal/generate_link"))
        .withRequestBody(matchingJsonPath("$.organization"))
    )
  }

  @Test
  fun `generateLink translates 401 to UnauthorizedException`() {
    stubResponse("POST", "/portal/generate_link", 401)
    assertThrows(UnauthorizedException::class.java) {
      api().generateLink("sample-arg")
    }
  }

  @Test
  fun `generateLink translates 404 to NotFoundException`() {
    stubResponse("POST", "/portal/generate_link", 404)
    assertThrows(NotFoundException::class.java) {
      api().generateLink("sample-arg")
    }
  }

  @Test
  fun `generateLink translates 429 to RateLimitException`() {
    stubResponse("POST", "/portal/generate_link", 429)
    assertThrows(RateLimitException::class.java) {
      api().generateLink("sample-arg")
    }
  }

  @Test
  fun `generateLink translates 500 to GenericServerException`() {
    stubResponse("POST", "/portal/generate_link", 500)
    assertThrows(GenericServerException::class.java) {
      api().generateLink("sample-arg")
    }
  }
}
