// This file is auto-generated by oagen. Do not edit.

package com.workos.types

import com.fasterxml.jackson.annotation.JsonEnumDefaultValue
import com.fasterxml.jackson.annotation.JsonValue

/** Enumeration of valid ApplicationsRegistrationTypes values returned or accepted by the API. */
enum class ApplicationsRegistrationTypes(
  /** The wire value sent to and received from the API. */
  @JsonValue val value: String
) {
  @JsonEnumDefaultValue
  Unknown("unknown"),
  Dynamic("dynamic"),
  Authenticated("authenticated")
}
