// This file is auto-generated by oagen. Do not edit.

package com.workos.types

import com.fasterxml.jackson.annotation.JsonValue

/** ConnectionDeactivatedDataState enum. */
enum class ConnectionDeactivatedDataState(
  @JsonValue val value: String
) {
  Unknown("unknown"),
  Draft("draft"),
  Active("active"),
  Validating("validating"),
  Inactive("inactive"),
  Deleting("deleting")
}
