// This file is auto-generated by oagen. Do not edit.

package com.workos.types

import com.fasterxml.jackson.annotation.JsonValue

/** ConnectedAccountState enum. */
enum class ConnectedAccountState(
  @JsonValue val value: String
) {
  Unknown("unknown"),
  Connected("connected"),
  NeedsReauthorization("needs_reauthorization"),
  Disconnected("disconnected")
}
