// This file is auto-generated by oagen. Do not edit.

package com.workos.types

import com.fasterxml.jackson.annotation.JsonEnumDefaultValue
import com.fasterxml.jackson.annotation.JsonValue

/** Enumeration of valid ConnectionDeactivatedDataState values returned or accepted by the API. */
enum class ConnectionDeactivatedDataState(
  @JsonValue val value: String
) {
  @JsonEnumDefaultValue
  Unknown("unknown"),
  Draft("draft"),
  Active("active"),
  Validating("validating"),
  Inactive("inactive"),
  Deleting("deleting")
}
