// This file is auto-generated by oagen. Do not edit.

package com.workos.types

import com.fasterxml.jackson.annotation.JsonValue

/** DsyncActivatedDataState enum. */
enum class DsyncActivatedDataState(
  @JsonValue val value: String
) {
  Unknown("unknown"),
  Active("active"),
  Validating("validating"),
  InvalidCredentials("invalid_credentials"),
  Inactive("inactive"),
  Deleting("deleting")
}
