// This file is auto-generated by oagen. Do not edit.

package com.workos.types

import com.fasterxml.jackson.annotation.JsonValue

/** InvitationAcceptedDataState enum. */
enum class InvitationAcceptedDataState(
  @JsonValue val value: String
) {
  Unknown("unknown"),
  Pending("pending"),
  Accepted("accepted"),
  Expired("expired"),
  Revoked("revoked")
}
