// This file is auto-generated by oagen. Do not edit.

package com.workos.types

import com.fasterxml.jackson.annotation.JsonValue

/** OrganizationDeletedDataDomainVerificationStrategy enum. */
enum class OrganizationDeletedDataDomainVerificationStrategy(
  @JsonValue val value: String
) {
  Unknown("unknown"),
  Dns("dns"),
  Manual("manual")
}
