// This file is auto-generated by oagen. Do not edit.

package com.workos.types

import com.fasterxml.jackson.annotation.JsonValue

/** RadarStandaloneResponseControl enum. */
enum class RadarStandaloneResponseControl(
  @JsonValue val value: String
) {
  Unknown("unknown"),
  BotDetection("bot_detection"),
  BruteForceAttack("brute_force_attack"),
  CredentialStuffing("credential_stuffing"),
  DomainSignUpRateLimit("domain_sign_up_rate_limit"),
  IpSignUpRateLimit("ip_sign_up_rate_limit"),
  ImpossibleTravel("impossible_travel"),
  RepeatSignUp("repeat_sign_up"),
  StaleAccount("stale_account"),
  UnrecognizedDevice("unrecognized_device"),
  Restriction("restriction")
}
