// This file is auto-generated by oagen. Do not edit.

package com.workos.types

import com.fasterxml.jackson.annotation.JsonValue

/** RoleType enum. */
enum class RoleType(
  @JsonValue val value: String
) {
  Unknown("unknown"),
  EnvironmentRole("EnvironmentRole"),
  OrganizationRole("OrganizationRole")
}
