// This file is auto-generated by oagen. Do not edit.

package com.workos.types

import com.fasterxml.jackson.annotation.JsonEnumDefaultValue
import com.fasterxml.jackson.annotation.JsonValue

/** Enumeration of valid SSOProvider values returned or accepted by the API. */
enum class SSOProvider(
  /** The wire value sent to and received from the API. */
  @JsonValue val value: String
) {
  @JsonEnumDefaultValue
  Unknown("unknown"),
  AppleOAuth("AppleOAuth"),
  BitbucketOAuth("BitbucketOAuth"),
  GitHubOAuth("GitHubOAuth"),
  GitLabOAuth("GitLabOAuth"),
  GoogleOAuth("GoogleOAuth"),
  IntuitOAuth("IntuitOAuth"),
  LinkedInOAuth("LinkedInOAuth"),
  MicrosoftOAuth("MicrosoftOAuth"),
  SalesforceOAuth("SalesforceOAuth"),
  SlackOAuth("SlackOAuth"),
  VercelMarketplaceOAuth("VercelMarketplaceOAuth"),
  VercelOAuth("VercelOAuth"),
  XeroOAuth("XeroOAuth")
}
