// This file is auto-generated by oagen. Do not edit.

package com.workos.types

import com.fasterxml.jackson.annotation.JsonValue

/** UserManagementAuthenticationScreenHint enum. */
enum class UserManagementAuthenticationScreenHint(
  @JsonValue val value: String
) {
  Unknown("unknown"),
  SignUp("sign-up"),
  SignIn("sign-in")
}
