// This file is auto-generated by oagen. Do not edit.

package com.workos.types

import com.fasterxml.jackson.annotation.JsonValue

/** UserManagementAuthenticationProvider enum. */
enum class UserManagementAuthenticationProvider(
  @JsonValue val value: String
) {
  Unknown("unknown"),
  Authkit("authkit"),
  AppleOAuth("AppleOAuth"),
  GitHubOAuth("GitHubOAuth"),
  GoogleOAuth("GoogleOAuth"),
  MicrosoftOAuth("MicrosoftOAuth")
}
