// This file is auto-generated by oagen. Do not edit.

package com.workos.types

import com.fasterxml.jackson.annotation.JsonValue

/** VaultDekReadDataActorSource enum. */
enum class VaultDekReadDataActorSource(
  @JsonValue val value: String
) {
  Unknown("unknown"),
  Api("api"),
  Dashboard("dashboard")
}
