// This file is auto-generated by oagen. Do not edit.

package com.workos.pipesprovider

import com.workos.common.exceptions.GenericServerException
import com.workos.common.exceptions.NotFoundException
import com.workos.common.exceptions.RateLimitException
import com.workos.common.exceptions.UnauthorizedException
import com.workos.test.TestBase
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Test

class PipesProviderTest : TestBase() {
  private fun api() = PipesProvider(createWorkOSClient())

  @Test
  fun `listOrganizationDataIntegrationConfigurations returns a typed response`() {
    stubResponse("GET", "/organizations/sample-arg/data_integration_configurations", 200, "{\"object\": \"list\", \"data\": []}")
    val result = api().listOrganizationDataIntegrationConfigurations("sample-arg")
    assertNotNull(result)
    assertEquals("list", result.objectType)
  }

  @Test
  fun `updateOrganizationDataIntegrationConfiguration returns a typed response`() {
    stubResponse(
      "PUT",
      "/organizations/sample-arg/data_integration_configurations/sample-arg",
      200,
      "{\"object\": \"data_integration_configuration\", \"id\": \"sample\", \"organization_id\": \"sample\", \"slug\": \"sample\", " +
        "\"name\": \"sample\", \"enabled\": false, \"scopes\": null, \"created_at\": \"sample\", \"updated_at\": \"sample\"}"
    )
    val result = api().updateOrganizationDataIntegrationConfiguration("sample-arg", "sample-arg")
    assertNotNull(result)
    assertEquals("data_integration_configuration", result.objectType)
    assertEquals("sample", result.id)
    assertEquals("sample", result.organizationId)
    assertEquals("sample", result.slug)
    assertEquals("sample", result.name)
  }

  @Test
  fun `listOrganizationDataIntegrationConfigurations translates 401 to UnauthorizedException`() {
    stubResponse("GET", "/organizations/sample-arg/data_integration_configurations", 401)
    assertThrows(UnauthorizedException::class.java) {
      api().listOrganizationDataIntegrationConfigurations("sample-arg")
    }
  }

  @Test
  fun `listOrganizationDataIntegrationConfigurations translates 404 to NotFoundException`() {
    stubResponse("GET", "/organizations/sample-arg/data_integration_configurations", 404)
    assertThrows(NotFoundException::class.java) {
      api().listOrganizationDataIntegrationConfigurations("sample-arg")
    }
  }

  @Test
  fun `listOrganizationDataIntegrationConfigurations translates 429 to RateLimitException`() {
    stubResponse("GET", "/organizations/sample-arg/data_integration_configurations", 429)
    assertThrows(RateLimitException::class.java) {
      api().listOrganizationDataIntegrationConfigurations("sample-arg")
    }
  }

  @Test
  fun `listOrganizationDataIntegrationConfigurations translates 500 to GenericServerException`() {
    stubResponse("GET", "/organizations/sample-arg/data_integration_configurations", 500)
    assertThrows(GenericServerException::class.java) {
      api().listOrganizationDataIntegrationConfigurations("sample-arg")
    }
  }
}
