// This file is auto-generated by oagen. Do not edit.

package com.workos.connect

import com.github.tomakehurst.wiremock.client.WireMock.aResponse
import com.github.tomakehurst.wiremock.client.WireMock.get
import com.github.tomakehurst.wiremock.client.WireMock.post
import com.github.tomakehurst.wiremock.client.WireMock.put
import com.github.tomakehurst.wiremock.client.WireMock.urlPathMatching
import com.workos.common.exceptions.GenericServerException
import com.workos.common.exceptions.NotFoundException
import com.workos.common.exceptions.RateLimitException
import com.workos.common.exceptions.UnauthorizedException
import com.workos.test.TestBase
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Test

class ConnectTest : TestBase() {
  private fun api() = Connect(createWorkOSClient())

  @Test
  fun `listApplications returns a typed response`() {
    wireMockRule.stubFor(
      get(urlPathMatching("/connect/applications"))
        .willReturn(
          aResponse()
            .withStatus(200)
            .withHeader("Content-Type", "application/json")
            .withBody("{\"data\": [], \"list_metadata\": {\"before\": null, \"after\": null}}")
        )
    )
    val result = api().listApplications()
    assertNotNull(result)
  }

  @Test
  fun `createOAuthApplication returns a typed response`() {
    wireMockRule.stubFor(
      post(urlPathMatching("/connect/applications"))
        .willReturn(
          aResponse()
            .withStatus(200)
            .withHeader("Content-Type", "application/json")
            .withBody(
              "{\"object\": \"connect_application\", \"id\": \"sample\", \"client_id\": \"sample\", \"description\": null, \"name\": " +
                "\"sample\", \"scopes\": [], \"created_at\": \"2024-01-01T00:00:00Z\", \"updated_at\": \"2024-01-01T00:00:00Z\"}"
            )
        )
    )
    val result = api().createOAuthApplication("sample-arg", false)
    assertNotNull(result)
  }

  @Test
  fun `createM2MApplication returns a typed response`() {
    wireMockRule.stubFor(
      post(urlPathMatching("/connect/applications"))
        .willReturn(
          aResponse()
            .withStatus(200)
            .withHeader("Content-Type", "application/json")
            .withBody(
              "{\"object\": \"connect_application\", \"id\": \"sample\", \"client_id\": \"sample\", \"description\": null, \"name\": " +
                "\"sample\", \"scopes\": [], \"created_at\": \"2024-01-01T00:00:00Z\", \"updated_at\": \"2024-01-01T00:00:00Z\"}"
            )
        )
    )
    val result = api().createM2MApplication("sample-arg", "sample-arg")
    assertNotNull(result)
  }

  @Test
  fun `getApplication returns a typed response`() {
    wireMockRule.stubFor(
      get(urlPathMatching("/connect/applications/sample-arg"))
        .willReturn(
          aResponse()
            .withStatus(200)
            .withHeader("Content-Type", "application/json")
            .withBody(
              "{\"object\": \"connect_application\", \"id\": \"sample\", \"client_id\": \"sample\", \"description\": null, \"name\": " +
                "\"sample\", \"scopes\": [], \"created_at\": \"2024-01-01T00:00:00Z\", \"updated_at\": \"2024-01-01T00:00:00Z\"}"
            )
        )
    )
    val result = api().getApplication("sample-arg")
    assertNotNull(result)
  }

  @Test
  fun `updateApplication returns a typed response`() {
    wireMockRule.stubFor(
      put(urlPathMatching("/connect/applications/sample-arg"))
        .willReturn(
          aResponse()
            .withStatus(200)
            .withHeader("Content-Type", "application/json")
            .withBody(
              "{\"object\": \"connect_application\", \"id\": \"sample\", \"client_id\": \"sample\", \"description\": null, \"name\": " +
                "\"sample\", \"scopes\": [], \"created_at\": \"2024-01-01T00:00:00Z\", \"updated_at\": \"2024-01-01T00:00:00Z\"}"
            )
        )
    )
    val result = api().updateApplication("sample-arg")
    assertNotNull(result)
  }

  @Test
  fun `listApplicationClientSecrets returns a typed response`() {
    wireMockRule.stubFor(
      get(urlPathMatching("/connect/applications/sample-arg/client_secrets"))
        .willReturn(
          aResponse()
            .withStatus(200)
            .withHeader("Content-Type", "application/json")
            .withBody(
              "{\"object\": \"connect_application_secret\", \"id\": \"sample\", \"secret_hint\": \"sample\", \"last_used_at\": null, " +
                "\"created_at\": \"2024-01-01T00:00:00Z\", \"updated_at\": \"2024-01-01T00:00:00Z\"}"
            )
        )
    )
    val result = api().listApplicationClientSecrets("sample-arg")
    assertNotNull(result)
  }

  @Test
  fun `createApplicationClientSecret returns a typed response`() {
    wireMockRule.stubFor(
      post(urlPathMatching("/connect/applications/sample-arg/client_secrets"))
        .willReturn(
          aResponse()
            .withStatus(200)
            .withHeader("Content-Type", "application/json")
            .withBody(
              "{\"object\": \"connect_application_secret\", \"id\": \"sample\", \"secret_hint\": \"sample\", \"last_used_at\": null, " +
                "\"created_at\": \"2024-01-01T00:00:00Z\", \"updated_at\": \"2024-01-01T00:00:00Z\", \"secret\": \"sample\"}"
            )
        )
    )
    val result = api().createApplicationClientSecret("sample-arg")
    assertNotNull(result)
  }

  @Test
  fun `listApplications translates 401 to UnauthorizedException`() {
    wireMockRule.stubFor(
      get(urlPathMatching("/connect/applications"))
        .willReturn(
          aResponse()
            .withStatus(401)
            .withHeader("Content-Type", "application/json")
            .withBody("{}")
        )
    )
    assertThrows(UnauthorizedException::class.java) {
      api().listApplications()
    }
  }

  @Test
  fun `listApplications translates 404 to NotFoundException`() {
    wireMockRule.stubFor(
      get(urlPathMatching("/connect/applications"))
        .willReturn(
          aResponse()
            .withStatus(404)
            .withHeader("Content-Type", "application/json")
            .withBody("{}")
        )
    )
    assertThrows(NotFoundException::class.java) {
      api().listApplications()
    }
  }

  @Test
  fun `listApplications translates 429 to RateLimitException`() {
    wireMockRule.stubFor(
      get(urlPathMatching("/connect/applications"))
        .willReturn(
          aResponse()
            .withStatus(429)
            .withHeader("Content-Type", "application/json")
            .withBody("{}")
        )
    )
    assertThrows(RateLimitException::class.java) {
      api().listApplications()
    }
  }

  @Test
  fun `listApplications translates 500 to GenericServerException`() {
    wireMockRule.stubFor(
      get(urlPathMatching("/connect/applications"))
        .willReturn(
          aResponse()
            .withStatus(500)
            .withHeader("Content-Type", "application/json")
            .withBody("{}")
        )
    )
    assertThrows(GenericServerException::class.java) {
      api().listApplications()
    }
  }
}
