// This file is auto-generated by oagen. Do not edit.

package com.workos.organizationdomains

import com.github.tomakehurst.wiremock.client.WireMock.aResponse
import com.github.tomakehurst.wiremock.client.WireMock.get
import com.github.tomakehurst.wiremock.client.WireMock.urlPathMatching
import com.workos.common.exceptions.GenericServerException
import com.workos.common.exceptions.NotFoundException
import com.workos.common.exceptions.RateLimitException
import com.workos.common.exceptions.UnauthorizedException
import com.workos.test.TestBase
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Test

class OrganizationDomainsTest : TestBase() {
  private fun api() = OrganizationDomains(createWorkOSClient())

  @Test
  fun `get translates 401 to UnauthorizedException`() {
    wireMockRule.stubFor(
      get(urlPathMatching("/organization_domains/sample-arg"))
        .willReturn(
          aResponse()
            .withStatus(401)
            .withHeader("Content-Type", "application/json")
            .withBody("{}")
        )
    )
    assertThrows(UnauthorizedException::class.java) {
      api().get("sample-arg")
    }
  }

  @Test
  fun `get translates 404 to NotFoundException`() {
    wireMockRule.stubFor(
      get(urlPathMatching("/organization_domains/sample-arg"))
        .willReturn(
          aResponse()
            .withStatus(404)
            .withHeader("Content-Type", "application/json")
            .withBody("{}")
        )
    )
    assertThrows(NotFoundException::class.java) {
      api().get("sample-arg")
    }
  }

  @Test
  fun `get translates 429 to RateLimitException`() {
    wireMockRule.stubFor(
      get(urlPathMatching("/organization_domains/sample-arg"))
        .willReturn(
          aResponse()
            .withStatus(429)
            .withHeader("Content-Type", "application/json")
            .withBody("{}")
        )
    )
    assertThrows(RateLimitException::class.java) {
      api().get("sample-arg")
    }
  }

  @Test
  fun `get translates 500 to GenericServerException`() {
    wireMockRule.stubFor(
      get(urlPathMatching("/organization_domains/sample-arg"))
        .willReturn(
          aResponse()
            .withStatus(500)
            .withHeader("Content-Type", "application/json")
            .withBody("{}")
        )
    )
    assertThrows(GenericServerException::class.java) {
      api().get("sample-arg")
    }
  }
}
