// This file is auto-generated by oagen. Do not edit.

package com.workos.sso

import com.github.tomakehurst.wiremock.client.WireMock.getRequestedFor
import com.github.tomakehurst.wiremock.client.WireMock.matching
import com.github.tomakehurst.wiremock.client.WireMock.matchingJsonPath
import com.github.tomakehurst.wiremock.client.WireMock.postRequestedFor
import com.github.tomakehurst.wiremock.client.WireMock.urlPathMatching
import com.workos.common.exceptions.GenericServerException
import com.workos.common.exceptions.NotFoundException
import com.workos.common.exceptions.RateLimitException
import com.workos.common.exceptions.UnauthorizedException
import com.workos.test.TestBase
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test

class SSOTest : TestBase() {
  private fun api() = SSO(createWorkOSClient())

  @Test
  fun `listConnections returns a typed response`() {
    stubResponse("GET", "/connections", 200, "{\"data\": [], \"list_metadata\": {\"before\": null, \"after\": null}}")
    val result = api().listConnections()
    assertNotNull(result)
  }

  @Test
  fun `getConnection returns a typed response`() {
    stubResponse(
      "GET",
      "/connections/sample-arg",
      200,
      "{\"object\": \"connection\", \"id\": \"sample\", \"connection_type\": \"Pending\", \"name\": \"sample\", \"state\": " +
        "\"requires_type\", \"status\": \"linked\", \"domains\": [], \"created_at\": \"2024-01-01T00:00:00Z\", \"updated_at\": " +
        "\"2024-01-01T00:00:00Z\"}"
    )
    val result = api().getConnection("sample-arg")
    assertNotNull(result)
  }

  @Test
  @Disabled("generator: could not synthesize required arguments for deleteConnection")
  fun `deleteConnection returns a typed response`() {
    // Intentionally empty: the generator could not synthesize required arguments.
  }

  @Test
  fun `authorizeLogout returns a typed response`() {
    stubResponse("POST", "/sso/logout/authorize", 200, "{\"logout_url\": \"sample\", \"logout_token\": \"sample\"}")
    val result = api().authorizeLogout("sample-arg")
    assertNotNull(result)
    wireMockRule.verify(
      postRequestedFor(urlPathMatching("/sso/logout/authorize"))
        .withRequestBody(matchingJsonPath("$.profile_id"))
    )
  }

  @Test
  fun `getProfile returns a typed response`() {
    stubResponse(
      "GET",
      "/sso/profile",
      200,
      "{\"object\": \"profile\", \"id\": \"sample\", \"organization_id\": null, \"connection_id\": \"sample\", \"connection_type\": " +
        "\"Pending\", \"idp_id\": \"sample\", \"email\": \"sample\", \"first_name\": null, \"last_name\": null, \"raw_attributes\": {}}"
    )
    val result = api().getProfile()
    assertNotNull(result)
  }

  @Test
  fun `getProfileAndToken returns a typed response`() {
    stubResponse(
      "POST",
      "/sso/token",
      200,
      "{\"token_type\": \"Bearer\", \"access_token\": \"sample\", \"expires_in\": 0, \"profile\": {\"object\": \"profile\", \"id\": " +
        "\"sample\", \"organization_id\": null, \"connection_id\": \"sample\", \"connection_type\": \"Pending\", \"idp_id\": \"sample\", " +
        "\"email\": \"sample\", \"first_name\": null, \"last_name\": null, \"raw_attributes\": {}}}"
    )
    val result = api().getProfileAndToken("sample-arg", "sample-arg")
    assertNotNull(result)
    wireMockRule.verify(
      postRequestedFor(urlPathMatching("/sso/token"))
        .withRequestBody(matchingJsonPath("$.code"))
        .withQueryParam("code", matching("sample-arg"))
    )
  }

  @Test
  fun `listConnections translates 401 to UnauthorizedException`() {
    stubResponse("GET", "/connections", 401)
    assertThrows(UnauthorizedException::class.java) {
      api().listConnections()
    }
  }

  @Test
  fun `listConnections translates 404 to NotFoundException`() {
    stubResponse("GET", "/connections", 404)
    assertThrows(NotFoundException::class.java) {
      api().listConnections()
    }
  }

  @Test
  fun `listConnections translates 429 to RateLimitException`() {
    stubResponse("GET", "/connections", 429)
    assertThrows(RateLimitException::class.java) {
      api().listConnections()
    }
  }

  @Test
  fun `listConnections translates 500 to GenericServerException`() {
    stubResponse("GET", "/connections", 500)
    assertThrows(GenericServerException::class.java) {
      api().listConnections()
    }
  }
}
