// This file is auto-generated by oagen. Do not edit.

package com.workos.webhooks

import com.github.tomakehurst.wiremock.client.WireMock.matchingJsonPath
import com.github.tomakehurst.wiremock.client.WireMock.postRequestedFor
import com.github.tomakehurst.wiremock.client.WireMock.urlPathMatching
import com.workos.common.exceptions.GenericServerException
import com.workos.common.exceptions.NotFoundException
import com.workos.common.exceptions.RateLimitException
import com.workos.common.exceptions.UnauthorizedException
import com.workos.test.TestBase
import com.workos.types.CreateWebhookEndpointEvents
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Test

class WebhooksServiceTest : TestBase() {
  private fun api() = Webhooks(createWorkOSClient())

  @Test
  fun `listEndpoints returns a typed response`() {
    stubResponse("GET", "/webhook_endpoints", 200, "{\"data\": [], \"list_metadata\": {\"before\": null, \"after\": null}}")
    val result = api().listEndpoints()
    assertNotNull(result)
  }

  @Test
  fun `createEndpoint returns a typed response`() {
    stubResponse(
      "POST",
      "/webhook_endpoints",
      200,
      "{\"object\": \"webhook_endpoint\", \"id\": \"sample\", \"endpoint_url\": \"sample\", \"secret\": \"sample\", \"status\": " +
        "\"enabled\", \"events\": [], \"created_at\": \"2024-01-01T00:00:00Z\", \"updated_at\": \"2024-01-01T00:00:00Z\"}"
    )
    val result = api().createEndpoint("sample-arg", emptyList<CreateWebhookEndpointEvents>())
    assertNotNull(result)
    assertEquals("webhook_endpoint", result.objectType)
    assertEquals("sample", result.id)
    assertEquals("sample", result.endpointUrl)
    assertEquals("sample", result.secret)
    wireMockRule.verify(
      postRequestedFor(urlPathMatching("/webhook_endpoints"))
        .withRequestBody(matchingJsonPath("$.endpoint_url"))
    )
  }

  @Test
  fun `updateEndpoint returns a typed response`() {
    stubResponse(
      "PATCH",
      "/webhook_endpoints/sample-arg",
      200,
      "{\"object\": \"webhook_endpoint\", \"id\": \"sample\", \"endpoint_url\": \"sample\", \"secret\": \"sample\", \"status\": " +
        "\"enabled\", \"events\": [], \"created_at\": \"2024-01-01T00:00:00Z\", \"updated_at\": \"2024-01-01T00:00:00Z\"}"
    )
    val result = api().updateEndpoint("sample-arg")
    assertNotNull(result)
    assertEquals("webhook_endpoint", result.objectType)
    assertEquals("sample", result.id)
    assertEquals("sample", result.endpointUrl)
    assertEquals("sample", result.secret)
  }

  @Test
  fun `deleteEndpoint completes without throwing`() {
    stubResponse("DELETE", "/webhook_endpoints/sample-arg", 204)
    api().deleteEndpoint("sample-arg")
  }

  @Test
  fun `listEndpoints translates 401 to UnauthorizedException`() {
    stubResponse("GET", "/webhook_endpoints", 401)
    assertThrows(UnauthorizedException::class.java) {
      api().listEndpoints()
    }
  }

  @Test
  fun `listEndpoints translates 404 to NotFoundException`() {
    stubResponse("GET", "/webhook_endpoints", 404)
    assertThrows(NotFoundException::class.java) {
      api().listEndpoints()
    }
  }

  @Test
  fun `listEndpoints translates 429 to RateLimitException`() {
    stubResponse("GET", "/webhook_endpoints", 429)
    assertThrows(RateLimitException::class.java) {
      api().listEndpoints()
    }
  }

  @Test
  fun `listEndpoints translates 500 to GenericServerException`() {
    stubResponse("GET", "/webhook_endpoints", 500)
    assertThrows(GenericServerException::class.java) {
      api().listEndpoints()
    }
  }
}
