// This file is auto-generated by oagen. Do not edit.

package com.workos.adminportal

import com.workos.WorkOS
import com.workos.common.http.RequestConfig
import com.workos.common.http.RequestOptions
import com.workos.common.http.bodyOf
import com.workos.models.IntentOptions
import com.workos.models.PortalLinkResponse
import com.workos.types.GenerateLinkIntent

/** API accessor for AdminPortal. */
class AdminPortal(
  internal val workos: WorkOS
) {
  /**
   * Generate a Portal Link
   *
   * Generate a Portal Link scoped to an Organization.
   *
   * @param organization An [Organization](https://workos.com/docs/reference/organization) identifier.
   * @param returnUrl The URL to go to when an admin clicks on your logo in the Admin Portal. If not specified, the return URL configured on the [Redirects](https://dashboard.workos.com/redirects) page will be used.
   * @param successUrl The URL to redirect the admin to when they finish setup. If not specified, the success URL configured on the [Redirects](https://dashboard.workos.com/redirects) page will be used.
   * @param intent The intent of the Admin Portal.
   * @param intentOptions Options to configure the Admin Portal based on the intent.
   * @param itContactEmails The email addresses of the IT contacts to grant access to the Admin Portal for the given organization. Accepts up to 20 emails.
   *
   * @return the PortalLinkResponse
   */
  @JvmOverloads
  fun generateLink(
    organization: String,
    returnUrl: String? = null,
    successUrl: String? = null,
    intent: GenerateLinkIntent? = null,
    intentOptions: IntentOptions? = null,
    itContactEmails: List<String>? = null,
    requestOptions: RequestOptions? = null
  ): PortalLinkResponse {
    val body =
      bodyOf(
        "organization" to organization,
        "return_url" to returnUrl,
        "success_url" to successUrl,
        "intent" to intent,
        "intent_options" to intentOptions,
        "it_contact_emails" to itContactEmails
      )
    val config =
      RequestConfig(
        method = "POST",
        path = "/portal/generate_link",
        body = body,
        requestOptions = requestOptions
      )
    return workos.baseClient.request(config, PortalLinkResponse::class.java)
  }
}
