name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build Kotlin SDK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # 6.0.3
      - name: Build
        run: |
          ./gradlew build

  test:
    name: Test Kotlin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # 6.0.3
      - name: Test
        run: |
          ./gradlew test --info
