name: Lint

on:
  push:
    branches:
      - 'main'
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint Kotlin SDK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # 6.1.0
      - name: Lint
        run: |
          ./gradlew ktlintCheck
